"""
전공별 기본 용어 사전 (DEFAULT_GLOSSARY)
- 각 전공의 핵심 영어 용어와 한국어 번역을 제공합니다.
- 사용자 커스텀 용어는 user_glossary.json에 별도 저장됩니다.
"""

DEFAULT_GLOSSARY = {

    # ─────────────────────────────────────────
    # 이과 (Science & Engineering)
    # ─────────────────────────────────────────

    "Data Science": {
        "Data Science": "데이터사이언스",
        "Machine Learning": "머신러닝",
        "Deep Learning": "딥러닝",
        "Neural Network": "신경망",
        "Backpropagation": "역전파",
        "Inference": "추론",
        "Overfitting": "과적합",
        "Underfitting": "과소적합",
        "Feature Engineering": "피처 엔지니어링",
        "Dimensionality Reduction": "차원 축소",
        "Principal Component Analysis": "주성분 분석",
        "Clustering": "군집화",
        "Classification": "분류",
        "Regression": "회귀",
        "Cross-validation": "교차 검증",
        "Hyperparameter": "하이퍼파라미터",
        "Parameter": "파라미터",
        "Gradient Descent": "경사 하강법",
        "Loss Function": "손실 함수",
        "Activation Function": "활성화 함수",
        "Exploratory Data Analysis": "탐색적 데이터 분석",
        "Data Preprocessing": "데이터 전처리",
        "Data Wrangling": "데이터 정제",
        "Outlier": "이상치",
        "Missing Value": "결측값",
        "Normalization": "정규화",
        "Standardization": "표준화",
        "Training Set": "훈련 세트",
        "Validation Set": "검증 세트",
        "Test Set": "테스트 세트",
        "Confusion Matrix": "혼동 행렬",
        "Precision": "정밀도",
        "Recall": "재현율",
        "F1 Score": "F1 점수",
        "ROC Curve": "ROC 곡선",
        "AUC": "AUC(곡선 아래 면적)",
        "Ensemble": "앙상블",
        "Random Forest": "랜덤 포레스트",
        "Boosting": "부스팅",
        "Bias": "편향",
        "Variance": "분산",
        "Structured": "정형",
        "Unstructured": "비정형",
        "Insights": "인사이트",
        "Pipeline": "파이프라인",
        "Algorithm": "알고리즘",
        "Multi-disciplinary": "다학제",
        "Domain": "도메인",
        "Introduction": "소개",
        "Key Components": "주요 구성 요소",
        "Programming": "프로그래밍",
    },

    "Artificial Intelligence Engineering": {
        "Artificial Intelligence": "인공지능",
        "Natural Language Processing": "자연어 처리",
        "Computer Vision": "컴퓨터 비전",
        "Reinforcement Learning": "강화학습",
        "Transformer": "트랜스포머",
        "Attention Mechanism": "어텐션 메커니즘",
        "Generative Model": "생성 모델",
        "Prompt Engineering": "프롬프트 엔지니어링",
        "Fine-tuning": "파인튜닝",
        "Pre-trained Model": "사전 학습 모델",
        "Transfer Learning": "전이 학습",
        "Object Detection": "객체 탐지",
        "Semantic Segmentation": "의미론적 분할",
        "Speech Recognition": "음성 인식",
        "Text Generation": "텍스트 생성",
        "Embedding": "임베딩",
        "Tokenization": "토크나이제이션",
        "Knowledge Graph": "지식 그래프",
        "Autonomous Agent": "자율 에이전트",
        "Reward Function": "보상 함수",
        "Policy": "정책",
        "Episode": "에피소드",
        "Inference Pipeline": "추론 파이프라인",
        "Hallucination": "환각(오류 생성)",
        "Benchmark": "벤치마크",
    },

    "Computer Science": {
        "Algorithm": "알고리즘",
        "Data Structure": "자료구조",
        "Time Complexity": "시간 복잡도",
        "Space Complexity": "공간 복잡도",
        "Recursion": "재귀",
        "Stack": "스택",
        "Queue": "큐",
        "Linked List": "연결 리스트",
        "Binary Tree": "이진 트리",
        "Graph": "그래프",
        "Sorting": "정렬",
        "Searching": "탐색",
        "Hashing": "해싱",
        "Dynamic Programming": "동적 프로그래밍",
        "Greedy Algorithm": "그리디 알고리즘",
        "Divide and Conquer": "분할 정복",
        "Operating System": "운영체제",
        "Process": "프로세스",
        "Thread": "스레드",
        "Deadlock": "교착 상태",
        "Semaphore": "세마포어",
        "Virtual Memory": "가상 메모리",
        "Cache": "캐시",
        "Database": "데이터베이스",
        "SQL": "SQL(구조적 질의 언어)",
        "Network": "네트워크",
        "Protocol": "프로토콜",
        "Encryption": "암호화",
        "API": "API(응용 프로그래밍 인터페이스)",
        "Object-Oriented Programming": "객체지향 프로그래밍",
        "Inheritance": "상속",
        "Polymorphism": "다형성",
        "Encapsulation": "캡슐화",
        "Abstraction": "추상화",
        "Version Control": "버전 관리",
        "Compiler": "컴파일러",
        "Interpreter": "인터프리터",
        "Debugging": "디버깅",
        "Refactoring": "리팩터링",
    },

    "Electrical Engineering": {
        "Circuit": "회로",
        "Voltage": "전압",
        "Current": "전류",
        "Resistance": "저항",
        "Capacitor": "커패시터",
        "Inductor": "인덕터",
        "Transistor": "트랜지스터",
        "Semiconductor": "반도체",
        "Diode": "다이오드",
        "Integrated Circuit": "집적 회로",
        "Microcontroller": "마이크로컨트롤러",
        "Signal Processing": "신호 처리",
        "Analog": "아날로그",
        "Digital": "디지털",
        "Frequency": "주파수",
        "Amplitude": "진폭",
        "Impedance": "임피던스",
        "Power Factor": "역률",
        "Transformer": "변압기",
        "Relay": "릴레이",
        "Feedback": "피드백",
        "PID Controller": "PID 제어기",
        "Oscilloscope": "오실로스코프",
        "Multimeter": "멀티미터",
        "PCB": "인쇄 회로 기판",
    },

    "Mechanical Engineering": {
        "Statics": "정역학",
        "Dynamics": "동역학",
        "Thermodynamics": "열역학",
        "Fluid Mechanics": "유체역학",
        "Stress": "응력",
        "Strain": "변형률",
        "Torque": "토크",
        "Friction": "마찰",
        "Momentum": "운동량",
        "Kinematics": "운동학",
        "Heat Transfer": "열전달",
        "Conduction": "전도",
        "Convection": "대류",
        "Radiation": "복사",
        "Material Science": "재료 공학",
        "Fatigue": "피로 파괴",
        "Yield Strength": "항복 강도",
        "Hardness": "경도",
        "Manufacturing": "제조",
        "CNC": "CNC(수치 제어 공작기계)",
        "CAD": "CAD(컴퓨터 지원 설계)",
        "Vibration": "진동",
        "Resonance": "공진",
        "Gear": "기어",
        "Bearing": "베어링",
    },

    "Chemical Engineering": {
        "Reaction Engineering": "반응 공학",
        "Mass Transfer": "물질 전달",
        "Heat Exchanger": "열교환기",
        "Distillation": "증류",
        "Absorption": "흡수",
        "Catalyst": "촉매",
        "Equilibrium": "평형",
        "Stoichiometry": "화학량론",
        "Thermodynamics": "열역학",
        "Fluid Flow": "유체 흐름",
        "Reactor": "반응기",
        "Yield": "수율",
        "Selectivity": "선택성",
        "Exothermic": "발열",
        "Endothermic": "흡열",
        "Phase Diagram": "상태도",
        "Polymer": "고분자",
        "Viscosity": "점도",
        "Diffusion": "확산",
        "Separation": "분리",
    },

    "Biotechnology": {
        "Genome": "유전체",
        "DNA": "DNA(디옥시리보핵산)",
        "RNA": "RNA(리보핵산)",
        "Protein": "단백질",
        "Enzyme": "효소",
        "Cell Culture": "세포 배양",
        "PCR": "PCR(중합효소 연쇄 반응)",
        "Gene Expression": "유전자 발현",
        "Mutation": "돌연변이",
        "Cloning": "클로닝",
        "Plasmid": "플라스미드",
        "Fermentation": "발효",
        "Bioreactor": "생물 반응기",
        "Antibody": "항체",
        "Antigen": "항원",
        "Stem Cell": "줄기세포",
        "CRISPR": "크리스퍼(유전자 편집 기술)",
        "Recombinant DNA": "재조합 DNA",
        "Electrophoresis": "전기영동",
        "Western Blot": "웨스턴 블롯",
    },

    "Mathematics": {
        "Calculus": "미적분학",
        "Differential Equation": "미분방정식",
        "Linear Algebra": "선형대수학",
        "Matrix": "행렬",
        "Eigenvalue": "고유값",
        "Eigenvector": "고유벡터",
        "Probability": "확률",
        "Statistics": "통계학",
        "Theorem": "정리",
        "Proof": "증명",
        "Integral": "적분",
        "Derivative": "도함수",
        "Limit": "극한",
        "Continuity": "연속성",
        "Convergence": "수렴",
        "Divergence": "발산",
        "Set Theory": "집합론",
        "Number Theory": "수론",
        "Topology": "위상수학",
        "Abstract Algebra": "추상대수학",
    },

    "Physics": {
        "Mechanics": "역학",
        "Electromagnetism": "전자기학",
        "Quantum Mechanics": "양자역학",
        "Relativity": "상대성 이론",
        "Thermodynamics": "열역학",
        "Wave": "파동",
        "Optics": "광학",
        "Nuclear Physics": "핵물리학",
        "Particle Physics": "입자물리학",
        "Momentum": "운동량",
        "Velocity": "속도",
        "Acceleration": "가속도",
        "Force": "힘",
        "Energy": "에너지",
        "Work": "일",
        "Power": "일률",
        "Entropy": "엔트로피",
        "Photon": "광자",
        "Electron": "전자",
        "Gravity": "중력",
    },

    "Medical": {
        "Anatomy": "해부학",
        "Physiology": "생리학",
        "Pathology": "병리학",
        "Pharmacology": "약리학",
        "Diagnosis": "진단",
        "Prognosis": "예후",
        "Etiology": "병인론",
        "Symptom": "증상",
        "Sign": "징후",
        "Treatment": "치료",
        "Inflammation": "염증",
        "Infection": "감염",
        "Immunity": "면역",
        "Cardiac": "심장의",
        "Pulmonary": "폐의",
        "Renal": "신장의",
        "Hepatic": "간의",
        "Neurological": "신경학적",
        "Surgical": "외과적",
        "Clinical Trial": "임상 시험",
        "Biopsy": "생검",
        "MRI": "자기공명영상",
        "CT Scan": "컴퓨터 단층촬영",
        "Hypertension": "고혈압",
        "Diabetes Mellitus": "당뇨병",
    },

    "Nursing": {
        "Assessment": "사정",
        "Diagnosis": "진단",
        "Planning": "계획",
        "Implementation": "수행",
        "Evaluation": "평가",
        "Intervention": "중재",
        "Outcome": "결과",
        "Vital Signs": "활력 징후",
        "Blood Pressure": "혈압",
        "Pulse": "맥박",
        "Respiration": "호흡",
        "Temperature": "체온",
        "Oxygen Saturation": "산소 포화도",
        "Medication": "투약",
        "Intravenous": "정맥 내",
        "Catheter": "카테터",
        "Wound Care": "상처 간호",
        "Infection Control": "감염 관리",
        "Aseptic Technique": "무균술",
        "Patient Safety": "환자 안전",
        "Documentation": "기록",
        "Informed Consent": "사전 동의",
        "Ethics": "윤리",
        "Holistic Care": "전인 간호",
        "Evidence-Based Practice": "근거 중심 실무",
    },

    "Architecture": {
        "Structural Analysis": "구조 해석",
        "Blueprint": "설계 도면",
        "Load Bearing": "하중 지지",
        "Foundation": "기초",
        "Beam": "보",
        "Column": "기둥",
        "Facade": "파사드(건물 외벽)",
        "Urban Planning": "도시 계획",
        "Zoning": "용도 지역",
        "Sustainability": "지속 가능성",
        "Green Building": "친환경 건물",
        "HVAC": "냉난방 및 환기 시스템",
        "Acoustics": "음향학",
        "Aesthetics": "미학",
        "Rendering": "렌더링",
        "BIM": "건물 정보 모델링",
        "Construction": "시공",
        "Renovation": "리노베이션",
        "Interior": "실내",
        "Exterior": "외부",
    },

    # ─────────────────────────────────────────
    # 문과 (Humanities)
    # ─────────────────────────────────────────

    "Business Administration": {
        "Asset": "자산",
        "Liability": "부채",
        "Equity": "자본",
        "Revenue": "매출",
        "Profit": "이익",
        "Net Income": "순이익",
        "Cash Flow": "현금 흐름",
        "Balance Sheet": "대차대조표",
        "Income Statement": "손익계산서",
        "ROI": "투자 수익률",
        "KPI": "핵심 성과 지표",
        "Supply Chain": "공급망",
        "Stakeholder": "이해관계자",
        "Corporate Governance": "기업 지배구조",
        "Merger": "합병",
        "Acquisition": "인수",
        "Strategic Planning": "전략 기획",
        "SWOT Analysis": "SWOT 분석",
        "Market Share": "시장 점유율",
        "Competitive Advantage": "경쟁 우위",
        "Outsourcing": "외주",
        "Entrepreneurship": "기업가 정신",
        "Venture Capital": "벤처 캐피털",
        "Budget": "예산",
        "Forecast": "예측",
    },

    "Economics": {
        "Supply": "공급",
        "Demand": "수요",
        "Equilibrium": "균형",
        "Elasticity": "탄력성",
        "Inflation": "인플레이션",
        "Deflation": "디플레이션",
        "GDP": "국내총생산",
        "GNP": "국민총생산",
        "Unemployment": "실업",
        "Fiscal Policy": "재정 정책",
        "Monetary Policy": "통화 정책",
        "Interest Rate": "금리",
        "Exchange Rate": "환율",
        "Trade Balance": "무역 수지",
        "Tariff": "관세",
        "Subsidy": "보조금",
        "Monopoly": "독점",
        "Oligopoly": "과점",
        "Perfect Competition": "완전 경쟁",
        "Market Failure": "시장 실패",
        "Externality": "외부 효과",
        "Public Good": "공공재",
        "Opportunity Cost": "기회 비용",
        "Marginal Cost": "한계 비용",
        "Consumer Surplus": "소비자 잉여",
    },

    "Marketing": {
        "Brand": "브랜드",
        "Target Market": "목표 시장",
        "Market Segmentation": "시장 세분화",
        "Positioning": "포지셔닝",
        "Consumer Behavior": "소비자 행동",
        "Marketing Mix": "마케팅 믹스",
        "Product": "제품",
        "Price": "가격",
        "Place": "유통",
        "Promotion": "촉진",
        "Advertising": "광고",
        "Digital Marketing": "디지털 마케팅",
        "Social Media": "소셜 미디어",
        "Content Marketing": "콘텐츠 마케팅",
        "SEO": "검색 엔진 최적화",
        "Customer Loyalty": "고객 충성도",
        "Customer Retention": "고객 유지",
        "Sales Funnel": "판매 깔때기",
        "Lead Generation": "리드 생성",
        "Conversion Rate": "전환율",
        "ROI": "투자 수익률",
        "Brand Equity": "브랜드 자산",
        "Value Proposition": "가치 제안",
        "AIDA Model": "AIDA 모델(주의-관심-욕구-행동)",
        "Market Research": "시장 조사",
    },

    "Accounting": {
        "Debit": "차변",
        "Credit": "대변",
        "Journal Entry": "분개",
        "Ledger": "원장",
        "Trial Balance": "시산표",
        "Balance Sheet": "대차대조표",
        "Income Statement": "손익계산서",
        "Cash Flow Statement": "현금흐름표",
        "Depreciation": "감가상각",
        "Amortization": "상각",
        "Audit": "감사",
        "GAAP": "일반회계기준",
        "IFRS": "국제회계기준",
        "Accrual": "발생주의",
        "Asset": "자산",
        "Liability": "부채",
        "Equity": "자본",
        "Revenue": "수익",
        "Expense": "비용",
        "Tax": "세금",
        "Inventory": "재고",
        "Accounts Receivable": "매출채권",
        "Accounts Payable": "매입채무",
        "Payroll": "급여",
        "Cost Accounting": "원가회계",
    },

    "Psychology": {
        "Cognition": "인지",
        "Behavior": "행동",
        "Emotion": "감정",
        "Motivation": "동기",
        "Perception": "지각",
        "Memory": "기억",
        "Attention": "주의",
        "Learning": "학습",
        "Conditioning": "조건화",
        "Reinforcement": "강화",
        "Punishment": "처벌",
        "Classical Conditioning": "고전적 조건화",
        "Operant Conditioning": "조작적 조건화",
        "Cognitive Dissonance": "인지 부조화",
        "Self-efficacy": "자기효능감",
        "Personality": "성격",
        "Trait": "특성",
        "Disorder": "장애",
        "Therapy": "치료",
        "Psychotherapy": "심리치료",
        "Cognitive Behavioral Therapy": "인지행동치료",
        "Unconscious": "무의식",
        "Stress": "스트레스",
        "Coping": "대처",
        "Resilience": "회복탄력성",
    },

    "International Relations": {
        "Sovereignty": "주권",
        "Diplomacy": "외교",
        "Globalization": "세계화",
        "Multilateralism": "다자주의",
        "Bilateral": "양자 간",
        "Geopolitics": "지정학",
        "Sanctions": "제재",
        "Treaty": "조약",
        "Alliance": "동맹",
        "Deterrence": "억지력",
        "Hegemony": "패권",
        "Soft Power": "소프트 파워",
        "Hard Power": "하드 파워",
        "Non-governmental Organization": "비정부 기구",
        "International Law": "국제법",
        "United Nations": "유엔",
        "Security Council": "안전보장이사회",
        "Refugee": "난민",
        "Human Rights": "인권",
        "Conflict Resolution": "분쟁 해결",
    },

    "Sociology": {
        "Social Structure": "사회 구조",
        "Social Class": "사회 계층",
        "Inequality": "불평등",
        "Norms": "규범",
        "Values": "가치",
        "Culture": "문화",
        "Socialization": "사회화",
        "Institution": "제도",
        "Deviance": "일탈",
        "Social Mobility": "사회 이동",
        "Ethnicity": "민족성",
        "Gender": "젠더",
        "Power": "권력",
        "Ideology": "이데올로기",
        "Capitalism": "자본주의",
        "Globalization": "세계화",
        "Community": "공동체",
        "Urbanization": "도시화",
        "Qualitative Research": "질적 연구",
        "Quantitative Research": "양적 연구",
    },

    "Media & Communication": {
        "Broadcasting": "방송",
        "Journalism": "저널리즘",
        "Media Literacy": "미디어 리터러시",
        "Framing": "프레이밍",
        "Agenda Setting": "의제 설정",
        "Public Relations": "홍보",
        "Propaganda": "선전",
        "Social Media": "소셜 미디어",
        "Audience": "수용자",
        "Content": "콘텐츠",
        "Narrative": "서사",
        "Discourse": "담론",
        "Convergence": "미디어 융합",
        "Digital Media": "디지털 미디어",
        "Censorship": "검열",
        "Freedom of Press": "언론 자유",
        "Infotainment": "인포테인먼트",
        "Fake News": "가짜 뉴스",
        "Engagement": "참여",
        "Influencer": "인플루언서",
    },

    "Political Science": {
        "Democracy": "민주주의",
        "Authoritarianism": "권위주의",
        "Legislature": "입법부",
        "Executive": "행정부",
        "Judiciary": "사법부",
        "Separation of Powers": "삼권분립",
        "Federalism": "연방주의",
        "Constitution": "헌법",
        "Election": "선거",
        "Voting": "투표",
        "Political Party": "정당",
        "Lobbying": "로비",
        "Policy": "정책",
        "Governance": "거버넌스",
        "Civil Society": "시민사회",
        "Bureaucracy": "관료제",
        "Totalitarianism": "전체주의",
        "Liberalism": "자유주의",
        "Conservatism": "보수주의",
        "Populism": "포퓰리즘",
    },

    # ─────────────────────────────────────────
    # 예체능 (Arts & Sports)
    # ─────────────────────────────────────────

    "Fine Arts": {
        "Composition": "구도",
        "Perspective": "원근법",
        "Chiaroscuro": "명암법",
        "Hue": "색조",
        "Saturation": "채도",
        "Value": "명도",
        "Texture": "질감",
        "Medium": "매체",
        "Canvas": "캔버스",
        "Pigment": "안료",
        "Impressionism": "인상주의",
        "Expressionism": "표현주의",
        "Abstract": "추상",
        "Figurative": "구상",
        "Portrait": "초상화",
        "Landscape": "풍경화",
        "Still Life": "정물화",
        "Sculpture": "조각",
        "Installation": "설치미술",
        "Critique": "비평",
    },

    "Graphic Design": {
        "Typography": "타이포그래피",
        "Layout": "레이아웃",
        "Grid": "그리드",
        "Hierarchy": "위계",
        "Contrast": "대비",
        "Alignment": "정렬",
        "White Space": "여백",
        "Color Theory": "색채 이론",
        "Brand Identity": "브랜드 아이덴티티",
        "Logo": "로고",
        "Icon": "아이콘",
        "Vector": "벡터",
        "Raster": "래스터",
        "Resolution": "해상도",
        "CMYK": "CMYK(인쇄 색상 모드)",
        "RGB": "RGB(화면 색상 모드)",
        "Mockup": "목업",
        "Prototype": "프로토타입",
        "User Interface": "사용자 인터페이스",
        "User Experience": "사용자 경험",
    },

    "Industrial Design": {
        "Ergonomics": "인체공학",
        "Form": "형태",
        "Function": "기능",
        "Prototype": "프로토타입",
        "Material": "소재",
        "Manufacturing Process": "제조 공정",
        "Sustainability": "지속 가능성",
        "User-centered Design": "사용자 중심 설계",
        "Ideation": "아이디어 발상",
        "Sketch": "스케치",
        "3D Modeling": "3D 모델링",
        "CAD": "컴퓨터 지원 설계",
        "Product Lifecycle": "제품 수명 주기",
        "Aesthetics": "심미성",
        "Usability": "사용성",
        "Tolerance": "공차",
        "Assembly": "조립",
        "Injection Molding": "사출 성형",
        "Rendering": "렌더링",
        "Market Research": "시장 조사",
    },

    "Music Composition": {
        "Harmony": "화성",
        "Melody": "선율",
        "Rhythm": "리듬",
        "Tempo": "빠르기",
        "Dynamics": "강약",
        "Timbre": "음색",
        "Counterpoint": "대위법",
        "Chord": "화음",
        "Scale": "음계",
        "Key Signature": "조표",
        "Time Signature": "박자표",
        "Modulation": "전조",
        "Cadence": "종지",
        "Motif": "동기",
        "Theme": "주제",
        "Variation": "변주",
        "Orchestration": "관현악법",
        "Notation": "악보 표기",
        "Polyphony": "다성음악",
        "Homophony": "단성 화성 음악",
    },

    "Physical Education": {
        "Cardiovascular Endurance": "심폐 지구력",
        "Muscular Strength": "근력",
        "Flexibility": "유연성",
        "Agility": "민첩성",
        "Coordination": "협응력",
        "Training": "훈련",
        "Aerobic": "유산소",
        "Anaerobic": "무산소",
        "Metabolism": "대사",
        "Nutrition": "영양",
        "Injury Prevention": "부상 예방",
        "Biomechanics": "생체역학",
        "Motor Learning": "운동 학습",
        "Periodization": "기간화 훈련",
        "Recovery": "회복",
        "Sports Psychology": "스포츠 심리학",
        "Team Dynamics": "팀 역학",
        "Tactics": "전술",
        "Fair Play": "페어플레이",
        "Performance Analysis": "퍼포먼스 분석",
    },

    "Film & Digital Media": {
        "Cinematography": "촬영술",
        "Editing": "편집",
        "Narrative": "서사",
        "Screenplay": "시나리오",
        "Direction": "연출",
        "Mise-en-scène": "미장센",
        "Montage": "몽타주",
        "Storyboard": "스토리보드",
        "Post-production": "후반 작업",
        "Visual Effects": "시각 효과",
        "Sound Design": "음향 디자인",
        "Color Grading": "색 보정",
        "Documentary": "다큐멘터리",
        "Genre": "장르",
        "Auteur": "작가주의",
        "Distribution": "배급",
        "Streaming": "스트리밍",
        "Frame Rate": "프레임 속도",
        "Resolution": "해상도",
        "Digital Asset": "디지털 자산",
    },

    "Fashion Design": {
        "Silhouette": "실루엣",
        "Draping": "드레이핑",
        "Textile": "직물",
        "Pattern Making": "패턴 제작",
        "Haute Couture": "오트 쿠튀르",
        "Ready-to-Wear": "기성복",
        "Trend": "트렌드",
        "Collection": "컬렉션",
        "Mood Board": "무드보드",
        "Lookbook": "룩북",
        "Sustainability": "지속 가능성",
        "Upcycling": "업사이클링",
        "Brand Identity": "브랜드 아이덴티티",
        "Color Palette": "컬러 팔레트",
        "Fabrication": "소재 구성",
        "Sewing": "봉제",
        "Seam": "솔기",
        "Hem": "단",
        "Runway": "런웨이",
        "Fashion Week": "패션 위크",
    },
}
