"""
전공별 기본 용어 사전 (DEFAULT_GLOSSARY)
- 각 전공의 핵심 영어 용어와 한국어 번역을 제공합니다. (과목별 100개)
- 사용자 커스텀 용어는 user_glossary.json에 별도 저장됩니다.
"""

DEFAULT_GLOSSARY = {

    # ─────────────────────────────────────────
    # 이과 (Science & Engineering)
    # ─────────────────────────────────────────

    "Data Science": {
        "Data Science": "데이터사이언스",
        "Machine Learning": "머신러닝",
        "Deep Learning": "딥러닝",
        "Neural Network": "신경망",
        "Backpropagation": "역전파",
        "Inference": "추론",
        "Overfitting": "과적합",
        "Underfitting": "과소적합",
        "Feature Engineering": "피처 엔지니어링",
        "Dimensionality Reduction": "차원 축소",
        "Principal Component Analysis": "주성분 분석",
        "Clustering": "군집화",
        "Classification": "분류",
        "Regression": "회귀",
        "Cross-validation": "교차 검증",
        "Hyperparameter": "하이퍼파라미터",
        "Parameter": "파라미터",
        "Gradient Descent": "경사 하강법",
        "Loss Function": "손실 함수",
        "Activation Function": "활성화 함수",
        "Exploratory Data Analysis": "탐색적 데이터 분석",
        "Data Preprocessing": "데이터 전처리",
        "Data Wrangling": "데이터 정제",
        "Outlier": "이상치",
        "Missing Value": "결측값",
        "Normalization": "정규화",
        "Standardization": "표준화",
        "Training Set": "훈련 세트",
        "Validation Set": "검증 세트",
        "Test Set": "테스트 세트",
        "Confusion Matrix": "혼동 행렬",
        "Precision": "정밀도",
        "Recall": "재현율",
        "F1 Score": "F1 점수",
        "ROC Curve": "ROC 곡선",
        "AUC": "AUC(곡선 아래 면적)",
        "Ensemble": "앙상블",
        "Random Forest": "랜덤 포레스트",
        "Boosting": "부스팅",
        "Bias": "편향",
        "Variance": "분산",
        "Structured Data": "정형 데이터",
        "Unstructured Data": "비정형 데이터",
        "Insights": "인사이트",
        "Pipeline": "파이프라인",
        "Algorithm": "알고리즘",
        "Multi-disciplinary": "다학제",
        "Domain": "도메인",
        "Introduction": "소개",
        "Key Components": "주요 구성 요소",
        "Programming": "프로그래밍",
        "Decision Tree": "의사결정 트리",
        "Support Vector Machine": "서포트 벡터 머신",
        "K-Nearest Neighbor": "K-최근접 이웃",
        "Naive Bayes": "나이브 베이즈",
        "Logistic Regression": "로지스틱 회귀",
        "Linear Regression": "선형 회귀",
        "Correlation": "상관관계",
        "Covariance": "공분산",
        "Histogram": "히스토그램",
        "Scatter Plot": "산점도",
        "Box Plot": "박스 플롯",
        "Heatmap": "히트맵",
        "Time Series": "시계열",
        "Seasonality": "계절성",
        "Trend": "추세",
        "Anomaly Detection": "이상 탐지",
        "Data Lake": "데이터 레이크",
        "Data Warehouse": "데이터 웨어하우스",
        "ETL": "ETL(추출·변환·적재)",
        "Big Data": "빅데이터",
        "Hadoop": "하둡",
        "Spark": "스파크",
        "SQL Query": "SQL 쿼리",
        "NoSQL": "NoSQL(비관계형 데이터베이스)",
        "API Integration": "API 연동",
        "Feature Selection": "피처 선택",
        "Feature Importance": "피처 중요도",
        "Sampling": "샘플링",
        "Imbalanced Dataset": "불균형 데이터셋",
        "SMOTE": "SMOTE(합성 오버샘플링)",
        "Label Encoding": "레이블 인코딩",
        "One-Hot Encoding": "원핫 인코딩",
        "Embedding": "임베딩",
        "Transfer Learning": "전이 학습",
        "Model Evaluation": "모델 평가",
        "Accuracy": "정확도",
        "Specificity": "특이도",
        "Mean Absolute Error": "평균 절대 오차",
        "Mean Squared Error": "평균 제곱 오차",
        "R-squared": "결정계수",
        "Regularization": "정규화(규제)",
        "Dropout": "드롭아웃",
        "Batch Size": "배치 크기",
        "Epoch": "에포크",
        "Learning Rate": "학습률",
        "Optimizer": "최적화기",
        "Data Augmentation": "데이터 증강",
        "Synthetic Data": "합성 데이터",
        "Model Interpretability": "모델 해석 가능성",
    },

    "Artificial Intelligence Engineering": {
        "Artificial Intelligence": "인공지능",
        "Natural Language Processing": "자연어 처리",
        "Computer Vision": "컴퓨터 비전",
        "Reinforcement Learning": "강화학습",
        "Transformer": "트랜스포머",
        "Attention Mechanism": "어텐션 메커니즘",
        "Generative Model": "생성 모델",
        "Prompt Engineering": "프롬프트 엔지니어링",
        "Fine-tuning": "파인튜닝",
        "Pre-trained Model": "사전 학습 모델",
        "Transfer Learning": "전이 학습",
        "Object Detection": "객체 탐지",
        "Semantic Segmentation": "의미론적 분할",
        "Speech Recognition": "음성 인식",
        "Text Generation": "텍스트 생성",
        "Embedding": "임베딩",
        "Tokenization": "토크나이제이션",
        "Knowledge Graph": "지식 그래프",
        "Autonomous Agent": "자율 에이전트",
        "Reward Function": "보상 함수",
        "Policy": "정책",
        "Episode": "에피소드",
        "Inference Pipeline": "추론 파이프라인",
        "Hallucination": "환각(오류 생성)",
        "Benchmark": "벤치마크",
        "Large Language Model": "거대 언어 모델",
        "Multimodal": "멀티모달",
        "Zero-shot Learning": "제로샷 학습",
        "Few-shot Learning": "퓨샷 학습",
        "Chain of Thought": "사고의 연쇄",
        "Retrieval-Augmented Generation": "검색 증강 생성",
        "Vector Database": "벡터 데이터베이스",
        "Convolutional Neural Network": "합성곱 신경망",
        "Recurrent Neural Network": "순환 신경망",
        "Long Short-Term Memory": "장단기 메모리",
        "Generative Adversarial Network": "생성적 적대 신경망",
        "Diffusion Model": "확산 모델",
        "Variational Autoencoder": "변분 오토인코더",
        "Image Classification": "이미지 분류",
        "Instance Segmentation": "인스턴스 분할",
        "Pose Estimation": "자세 추정",
        "Optical Character Recognition": "광학 문자 인식",
        "Named Entity Recognition": "개체명 인식",
        "Sentiment Analysis": "감성 분석",
        "Machine Translation": "기계 번역",
        "Text Summarization": "텍스트 요약",
        "Question Answering": "질의응답",
        "Chatbot": "챗봇",
        "Dialogue System": "대화 시스템",
        "Intent Classification": "의도 분류",
        "Slot Filling": "슬롯 채우기",
        "Word Embedding": "단어 임베딩",
        "Cosine Similarity": "코사인 유사도",
        "Beam Search": "빔 탐색",
        "Greedy Decoding": "그리디 디코딩",
        "Temperature Sampling": "온도 샘플링",
        "Top-k Sampling": "Top-k 샘플링",
        "Model Compression": "모델 압축",
        "Quantization": "양자화",
        "Knowledge Distillation": "지식 증류",
        "Federated Learning": "연합 학습",
        "Edge AI": "엣지 AI",
        "AI Ethics": "AI 윤리",
        "Explainable AI": "설명 가능한 AI",
        "Bias in AI": "AI 편향",
        "Fairness": "공정성",
        "Robustness": "강건성",
        "Adversarial Attack": "적대적 공격",
        "Data Poisoning": "데이터 오염",
        "Model Deployment": "모델 배포",
        "MLOps": "MLOps(머신러닝 운영)",
        "A/B Testing": "A/B 테스트",
        "Feature Store": "피처 스토어",
        "Model Registry": "모델 레지스트리",
        "Monitoring": "모니터링",
        "Drift Detection": "드리프트 탐지",
        "AutoML": "자동 머신러닝",
        "Neural Architecture Search": "신경망 구조 탐색",
        "Hyperparameter Tuning": "하이퍼파라미터 튜닝",
        "Bayesian Optimization": "베이즈 최적화",
        "Curriculum Learning": "교육과정 학습",
        "Self-supervised Learning": "자기지도 학습",
        "Contrastive Learning": "대조 학습",
        "Meta-learning": "메타 학습",
        "Domain Adaptation": "도메인 적응",
        "Active Learning": "능동 학습",
        "Semi-supervised Learning": "준지도 학습",
        "Graph Neural Network": "그래프 신경망",
        "Attention Head": "어텐션 헤드",
        "Positional Encoding": "위치 인코딩",
        "Layer Normalization": "레이어 정규화",
        "Residual Connection": "잔차 연결",
        "Cross-entropy Loss": "교차 엔트로피 손실",
        "Softmax": "소프트맥스",
        "RLHF": "인간 피드백 강화학습",
        "Instruction Tuning": "명령어 튜닝",
        "Multimodal Learning": "멀티모달 학습",
        "Semantic Search": "의미 검색",
        "Autonomous Driving": "자율주행",
        "Robotics": "로보틱스",
    },

    "Computer Science": {
        "Algorithm": "알고리즘",
        "Data Structure": "자료구조",
        "Time Complexity": "시간 복잡도",
        "Space Complexity": "공간 복잡도",
        "Recursion": "재귀",
        "Stack": "스택",
        "Queue": "큐",
        "Linked List": "연결 리스트",
        "Binary Tree": "이진 트리",
        "Graph": "그래프",
        "Sorting": "정렬",
        "Searching": "탐색",
        "Hashing": "해싱",
        "Dynamic Programming": "동적 프로그래밍",
        "Greedy Algorithm": "그리디 알고리즘",
        "Divide and Conquer": "분할 정복",
        "Operating System": "운영체제",
        "Process": "프로세스",
        "Thread": "스레드",
        "Deadlock": "교착 상태",
        "Semaphore": "세마포어",
        "Virtual Memory": "가상 메모리",
        "Cache": "캐시",
        "Database": "데이터베이스",
        "SQL": "SQL(구조적 질의 언어)",
        "Network": "네트워크",
        "Protocol": "프로토콜",
        "Encryption": "암호화",
        "API": "API(응용 프로그래밍 인터페이스)",
        "Object-Oriented Programming": "객체지향 프로그래밍",
        "Inheritance": "상속",
        "Polymorphism": "다형성",
        "Encapsulation": "캡슐화",
        "Abstraction": "추상화",
        "Version Control": "버전 관리",
        "Compiler": "컴파일러",
        "Interpreter": "인터프리터",
        "Debugging": "디버깅",
        "Refactoring": "리팩터링",
        "Binary Search": "이진 탐색",
        "Bubble Sort": "버블 정렬",
        "Merge Sort": "병합 정렬",
        "Quick Sort": "퀵 정렬",
        "Heap Sort": "힙 정렬",
        "Breadth-First Search": "너비 우선 탐색",
        "Depth-First Search": "깊이 우선 탐색",
        "Dijkstra Algorithm": "다익스트라 알고리즘",
        "Hash Table": "해시 테이블",
        "Priority Queue": "우선순위 큐",
        "Heap": "힙",
        "Trie": "트라이",
        "B-Tree": "B-트리",
        "Red-Black Tree": "레드-블랙 트리",
        "Pointer": "포인터",
        "Memory Allocation": "메모리 할당",
        "Garbage Collection": "가비지 컬렉션",
        "Concurrency": "동시성",
        "Parallelism": "병렬성",
        "Mutex": "뮤텍스",
        "Race Condition": "경쟁 조건",
        "Context Switching": "문맥 교환",
        "Scheduling": "스케줄링",
        "File System": "파일 시스템",
        "I/O": "입출력",
        "Socket": "소켓",
        "TCP/IP": "TCP/IP 프로토콜",
        "HTTP": "HTTP(하이퍼텍스트 전송 프로토콜)",
        "REST API": "REST API",
        "JSON": "JSON(자바스크립트 객체 표기법)",
        "XML": "XML(확장 가능한 마크업 언어)",
        "Cloud Computing": "클라우드 컴퓨팅",
        "Microservices": "마이크로서비스",
        "Docker": "도커(컨테이너 플랫폼)",
        "Kubernetes": "쿠버네티스",
        "CI/CD": "CI/CD(지속적 통합/배포)",
        "Unit Test": "단위 테스트",
        "Integration Test": "통합 테스트",
        "Design Pattern": "디자인 패턴",
        "Singleton": "싱글턴 패턴",
        "Factory Pattern": "팩토리 패턴",
        "Observer Pattern": "옵저버 패턴",
        "MVC": "MVC(모델-뷰-컨트롤러)",
        "Frontend": "프론트엔드",
        "Backend": "백엔드",
        "Full Stack": "풀스택",
        "Framework": "프레임워크",
        "Library": "라이브러리",
        "Dependency": "의존성",
        "Repository": "저장소",
        "Branch": "브랜치",
        "Merge": "병합",
        "Pull Request": "풀 리퀘스트",
        "Agile": "애자일",
        "Scrum": "스크럼",
        "Sprint": "스프린트",
        "Pseudocode": "의사코드",
        "Flowchart": "순서도",
        "UML": "UML(통합 모델링 언어)",
        "Concurrency Control": "동시성 제어",
        "Load Balancing": "부하 분산",
    },

    "Electrical Engineering": {
        "Circuit": "회로",
        "Voltage": "전압",
        "Current": "전류",
        "Resistance": "저항",
        "Capacitor": "커패시터",
        "Inductor": "인덕터",
        "Transistor": "트랜지스터",
        "Semiconductor": "반도체",
        "Diode": "다이오드",
        "Integrated Circuit": "집적 회로",
        "Microcontroller": "마이크로컨트롤러",
        "Signal Processing": "신호 처리",
        "Analog": "아날로그",
        "Digital": "디지털",
        "Frequency": "주파수",
        "Amplitude": "진폭",
        "Impedance": "임피던스",
        "Power Factor": "역률",
        "Transformer": "변압기",
        "Relay": "릴레이",
        "Feedback": "피드백",
        "PID Controller": "PID 제어기",
        "Oscilloscope": "오실로스코프",
        "Multimeter": "멀티미터",
        "PCB": "인쇄 회로 기판",
        "Ohm's Law": "옴의 법칙",
        "Kirchhoff's Voltage Law": "키르히호프 전압 법칙",
        "Kirchhoff's Current Law": "키르히호프 전류 법칙",
        "AC Circuit": "교류 회로",
        "DC Circuit": "직류 회로",
        "Rectifier": "정류기",
        "Inverter": "인버터",
        "Amplifier": "증폭기",
        "Operational Amplifier": "연산 증폭기",
        "Filter": "필터",
        "Low-pass Filter": "저역통과 필터",
        "High-pass Filter": "고역통과 필터",
        "Bandwidth": "대역폭",
        "Phase": "위상",
        "Resonance": "공진",
        "Inductance": "인덕턴스",
        "Capacitance": "커패시턴스",
        "Reactance": "리액턴스",
        "Power Dissipation": "전력 손실",
        "Ground": "접지",
        "Logic Gate": "논리 게이트",
        "Flip-flop": "플립플롭",
        "Multiplexer": "멀티플렉서",
        "Decoder": "디코더",
        "ADC": "아날로그-디지털 변환기",
        "DAC": "디지털-아날로그 변환기",
        "MOSFET": "금속산화물 반도체 전계효과 트랜지스터",
        "BJT": "양극성 접합 트랜지스터",
        "Zener Diode": "제너 다이오드",
        "LED": "발광 다이오드",
        "Photovoltaic Cell": "태양전지",
        "Electromagnetic Field": "전자기장",
        "Magnetic Flux": "자기 선속",
        "Faraday's Law": "패러데이 법칙",
        "Lenz's Law": "렌츠의 법칙",
        "Maxwell's Equations": "맥스웰 방정식",
        "Transmission Line": "전송선",
        "Antenna": "안테나",
        "Modulation": "변조",
        "Demodulation": "복조",
        "AM": "진폭 변조",
        "FM": "주파수 변조",
        "Digital Signal": "디지털 신호",
        "Analog Signal": "아날로그 신호",
        "Fourier Transform": "푸리에 변환",
        "Laplace Transform": "라플라스 변환",
        "Transfer Function": "전달 함수",
        "Bode Plot": "보드 선도",
        "Nyquist Criterion": "나이퀴스트 기준",
        "Sampling Rate": "샘플링 속도",
        "Noise": "잡음",
        "Signal-to-Noise Ratio": "신호 대 잡음비",
        "Power Supply": "전원 공급 장치",
        "Battery": "배터리",
        "Energy Storage": "에너지 저장",
        "Smart Grid": "스마트 그리드",
        "Embedded System": "임베디드 시스템",
        "FPGA": "현장 프로그래머블 게이트 어레이",
        "VHDL": "VHDL(하드웨어 기술 언어)",
        "Verilog": "베릴로그",
        "Simulation": "시뮬레이션",
        "Prototype": "프로토타입",
        "Soldering": "납땜",
        "Breadboard": "브레드보드",
        "Voltage Divider": "전압 분배기",
        "Wheatstone Bridge": "휘트스톤 브리지",
        "Thevenin's Theorem": "테브난 정리",
        "Norton's Theorem": "노턴 정리",
        "Superposition": "중첩의 원리",
        "Power Electronics": "전력 전자",
        "Motor Drive": "모터 드라이브",
        "Solar Panel": "태양광 패널",
        "Wireless Communication": "무선 통신",
        "Electromagnetic Compatibility": "전자기 적합성",
        "Grounding": "접지",
    },

    "Mechanical Engineering": {
        "Statics": "정역학",
        "Dynamics": "동역학",
        "Thermodynamics": "열역학",
        "Fluid Mechanics": "유체역학",
        "Stress": "응력",
        "Strain": "변형률",
        "Torque": "토크",
        "Friction": "마찰",
        "Momentum": "운동량",
        "Kinematics": "운동학",
        "Heat Transfer": "열전달",
        "Conduction": "전도",
        "Convection": "대류",
        "Radiation": "복사",
        "Material Science": "재료 공학",
        "Fatigue": "피로 파괴",
        "Yield Strength": "항복 강도",
        "Hardness": "경도",
        "Manufacturing": "제조",
        "CNC": "CNC(수치 제어 공작기계)",
        "CAD": "CAD(컴퓨터 지원 설계)",
        "Vibration": "진동",
        "Resonance": "공진",
        "Gear": "기어",
        "Bearing": "베어링",
        "Free Body Diagram": "자유 물체도",
        "Newton's Laws": "뉴턴의 법칙",
        "Equilibrium": "평형",
        "Center of Mass": "질량 중심",
        "Moment of Inertia": "관성 모멘트",
        "Angular Velocity": "각속도",
        "Angular Acceleration": "각가속도",
        "Work-Energy Theorem": "일-에너지 정리",
        "Conservation of Energy": "에너지 보존 법칙",
        "Potential Energy": "위치 에너지",
        "Kinetic Energy": "운동 에너지",
        "Power": "동력",
        "Efficiency": "효율",
        "Pressure": "압력",
        "Density": "밀도",
        "Viscosity": "점도",
        "Bernoulli's Equation": "베르누이 방정식",
        "Reynolds Number": "레이놀즈 수",
        "Turbulence": "난류",
        "Laminar Flow": "층류",
        "Drag Force": "항력",
        "Lift Force": "양력",
        "Compressibility": "압축성",
        "Enthalpy": "엔탈피",
        "Entropy": "엔트로피",
        "Carnot Cycle": "카르노 사이클",
        "Heat Engine": "열기관",
        "Rankine Cycle": "랭킨 사이클",
        "Refrigeration Cycle": "냉동 사이클",
        "Thermal Efficiency": "열효율",
        "Specific Heat": "비열",
        "Latent Heat": "잠열",
        "Tensile Strength": "인장 강도",
        "Compressive Strength": "압축 강도",
        "Shear Stress": "전단 응력",
        "Elastic Modulus": "탄성 계수",
        "Poisson's Ratio": "푸아송 비",
        "Plastic Deformation": "소성 변형",
        "Creep": "크리프",
        "Fracture Mechanics": "파괴 역학",
        "Corrosion": "부식",
        "Alloy": "합금",
        "Composite Material": "복합 재료",
        "Casting": "주조",
        "Forging": "단조",
        "Welding": "용접",
        "Machining": "절삭 가공",
        "Tolerance": "공차",
        "Assembly": "조립",
        "Spring Constant": "용수철 상수",
        "Damping": "감쇠",
        "Natural Frequency": "고유 진동수",
        "Mode Shape": "모드 형상",
        "Finite Element Analysis": "유한 요소 해석",
        "Simulation": "시뮬레이션",
        "Prototype": "시제품",
        "Quality Control": "품질 관리",
        "Six Sigma": "식스 시그마",
        "Lean Manufacturing": "린 제조",
        "3D Printing": "3D 프린팅",
        "Injection Molding": "사출 성형",
        "Hydraulics": "유압",
        "Pneumatics": "공압",
        "Linkage Mechanism": "링크 기구",
        "Cam": "캠",
        "Clutch": "클러치",
        "Brake": "브레이크",
        "Shaft": "축",
        "Coupling": "커플링",
        "Pulley": "풀리",
        "Belt Drive": "벨트 전동",
        "Chain Drive": "체인 전동",
        "Lubrication": "윤활",
        "Thermal Stress": "열응력",
        "Stress Concentration": "응력 집중",
    },

    "Chemical Engineering": {
        "Reaction Engineering": "반응 공학",
        "Mass Transfer": "물질 전달",
        "Heat Exchanger": "열교환기",
        "Distillation": "증류",
        "Absorption": "흡수",
        "Catalyst": "촉매",
        "Equilibrium": "평형",
        "Stoichiometry": "화학량론",
        "Thermodynamics": "열역학",
        "Fluid Flow": "유체 흐름",
        "Reactor": "반응기",
        "Yield": "수율",
        "Selectivity": "선택성",
        "Exothermic": "발열",
        "Endothermic": "흡열",
        "Phase Diagram": "상태도",
        "Polymer": "고분자",
        "Viscosity": "점도",
        "Diffusion": "확산",
        "Separation": "분리",
        "Batch Reactor": "회분식 반응기",
        "Continuous Stirred Tank Reactor": "연속 교반 탱크 반응기",
        "Plug Flow Reactor": "플러그 흐름 반응기",
        "Residence Time": "체류 시간",
        "Conversion": "전환율",
        "Rate Law": "반응 속도식",
        "Activation Energy": "활성화 에너지",
        "Arrhenius Equation": "아레니우스 방정식",
        "Reaction Rate": "반응 속도",
        "Mole Balance": "몰 수지",
        "Energy Balance": "에너지 수지",
        "Mass Balance": "물질 수지",
        "Steady State": "정상 상태",
        "Transient State": "비정상 상태",
        "Dimensionless Number": "무차원수",
        "Reynolds Number": "레이놀즈 수",
        "Nusselt Number": "누셀트 수",
        "Sherwood Number": "셔우드 수",
        "Prandtl Number": "프란틀 수",
        "Schmidt Number": "슈미트 수",
        "Packed Bed": "충전층",
        "Fluidized Bed": "유동층",
        "Tray Column": "단탑",
        "Reflux Ratio": "환류비",
        "Reboiler": "재비기",
        "Condenser": "응축기",
        "Stripping": "탈기",
        "Extraction": "추출",
        "Crystallization": "결정화",
        "Filtration": "여과",
        "Evaporation": "증발",
        "Drying": "건조",
        "Adsorption": "흡착",
        "Ion Exchange": "이온 교환",
        "Membrane Separation": "막 분리",
        "Osmosis": "삼투",
        "Reverse Osmosis": "역삼투",
        "Electrochemistry": "전기화학",
        "Electrolysis": "전기분해",
        "Corrosion": "부식",
        "Gibbs Free Energy": "깁스 자유 에너지",
        "Enthalpy": "엔탈피",
        "Entropy": "엔트로피",
        "Chemical Potential": "화학 퍼텐셜",
        "Fugacity": "퓨개시티",
        "Activity Coefficient": "활성도 계수",
        "Vapor-Liquid Equilibrium": "기액 평형",
        "Henry's Law": "헨리의 법칙",
        "Raoult's Law": "라울의 법칙",
        "Safety": "안전",
        "Hazard Analysis": "위험성 평가",
        "Process Control": "공정 제어",
        "PID Control": "PID 제어",
        "Instrumentation": "계장",
        "Piping and Instrumentation Diagram": "배관 계장 도면",
        "Scale-up": "규모 확대",
        "Pilot Plant": "파일럿 플랜트",
        "Process Simulation": "공정 시뮬레이션",
        "Equation of State": "상태 방정식",
        "Van der Waals": "반데르발스",
        "Critical Point": "임계점",
        "Triple Point": "삼중점",
        "Azeotrope": "공비 혼합물",
        "Surfactant": "계면활성제",
        "Emulsion": "에멀션",
        "Rheology": "유변학",
        "Non-Newtonian Fluid": "비뉴턴 유체",
        "Colloidal System": "콜로이드계",
        "Nanotechnology": "나노기술",
        "Green Chemistry": "녹색 화학",
        "Waste Treatment": "폐기물 처리",
        "Emission Control": "배출 제어",
        "Solvent": "용매",
        "Solute": "용질",
        "Concentration": "농도",
        "pH": "수소이온농도",
        "Acid-Base Reaction": "산-염기 반응",
        "Oxidation": "산화",
        "Reduction": "환원",
        "Redox Reaction": "산화-환원 반응",
    },

    "Biotechnology": {
        "Genome": "유전체",
        "DNA": "DNA(디옥시리보핵산)",
        "RNA": "RNA(리보핵산)",
        "Protein": "단백질",
        "Enzyme": "효소",
        "Cell Culture": "세포 배양",
        "PCR": "PCR(중합효소 연쇄 반응)",
        "Gene Expression": "유전자 발현",
        "Mutation": "돌연변이",
        "Cloning": "클로닝",
        "Plasmid": "플라스미드",
        "Fermentation": "발효",
        "Bioreactor": "생물 반응기",
        "Antibody": "항체",
        "Antigen": "항원",
        "Stem Cell": "줄기세포",
        "CRISPR": "크리스퍼(유전자 편집 기술)",
        "Recombinant DNA": "재조합 DNA",
        "Electrophoresis": "전기영동",
        "Western Blot": "웨스턴 블롯",
        "Transcription": "전사",
        "Translation": "번역",
        "Codon": "코돈",
        "Amino Acid": "아미노산",
        "Gene Therapy": "유전자 치료",
        "Biosensor": "바이오센서",
        "Biomarker": "바이오마커",
        "Proteomics": "단백질체학",
        "Genomics": "유전체학",
        "Metabolomics": "대사체학",
        "Bioinformatics": "생물정보학",
        "Sequencing": "염기서열 분석",
        "Next-generation Sequencing": "차세대 염기서열 분석",
        "Southern Blot": "서던 블롯",
        "Northern Blot": "노던 블롯",
        "Flow Cytometry": "유세포 분석",
        "ELISA": "효소결합 면역흡착 분석법",
        "Mass Spectrometry": "질량 분석법",
        "Chromatography": "크로마토그래피",
        "Centrifugation": "원심분리",
        "Microscopy": "현미경법",
        "Confocal Microscopy": "공초점 현미경",
        "Fluorescence": "형광",
        "Reporter Gene": "리포터 유전자",
        "Promoter": "프로모터",
        "Enhancer": "인핸서",
        "Silencer": "사일런서",
        "Intron": "인트론",
        "Exon": "엑손",
        "Splicing": "스플라이싱",
        "Epigenetics": "후성유전학",
        "Methylation": "메틸화",
        "Histone": "히스톤",
        "Chromatin": "염색질",
        "Chromosome": "염색체",
        "Mitosis": "유사분열",
        "Meiosis": "감수분열",
        "Apoptosis": "세포 사멸",
        "Cell Signaling": "세포 신호전달",
        "Receptor": "수용체",
        "Ligand": "리간드",
        "Second Messenger": "이차 전달자",
        "Kinase": "키나아제",
        "Phosphorylation": "인산화",
        "Glycolysis": "해당작용",
        "Citric Acid Cycle": "구연산 회로",
        "Oxidative Phosphorylation": "산화적 인산화",
        "Photosynthesis": "광합성",
        "Membrane": "막",
        "Lipid Bilayer": "인지질 이중층",
        "Transport Protein": "수송 단백질",
        "Organelle": "세포 소기관",
        "Mitochondria": "미토콘드리아",
        "Ribosome": "리보솜",
        "Endoplasmic Reticulum": "소포체",
        "Golgi Apparatus": "골지체",
        "Lysosome": "리소솜",
        "Vaccine": "백신",
        "Monoclonal Antibody": "단클론 항체",
        "Biopharmaceutical": "바이오의약품",
        "Biosimilar": "바이오시밀러",
        "Tissue Engineering": "조직공학",
        "Scaffold": "지지체",
        "Biodegradable": "생분해성",
        "Microbiome": "마이크로바이옴",
        "Metagenomics": "메타유전체학",
        "Synthetic Biology": "합성생물학",
        "Directed Evolution": "지향 진화",
        "Protein Engineering": "단백질 공학",
        "Enzyme Kinetics": "효소 반응속도론",
        "Km Value": "미카엘리스 상수",
        "Vmax": "최대 반응 속도",
        "Competitive Inhibition": "경쟁적 저해",
        "Allosteric Regulation": "알로스테릭 조절",
        "Cell Cycle": "세포 주기",
        "Checkpoints": "체크포인트",
        "Oncogene": "종양 유전자",
        "Tumor Suppressor Gene": "종양 억제 유전자",
        "Signal Transduction": "신호 전달",
        "Pathway": "신호 경로",
    },

    "Mathematics": {
        "Calculus": "미적분학",
        "Differential Equation": "미분방정식",
        "Linear Algebra": "선형대수학",
        "Matrix": "행렬",
        "Eigenvalue": "고유값",
        "Eigenvector": "고유벡터",
        "Probability": "확률",
        "Statistics": "통계학",
        "Theorem": "정리",
        "Proof": "증명",
        "Integral": "적분",
        "Derivative": "도함수",
        "Limit": "극한",
        "Continuity": "연속성",
        "Convergence": "수렴",
        "Divergence": "발산",
        "Set Theory": "집합론",
        "Number Theory": "수론",
        "Topology": "위상수학",
        "Abstract Algebra": "추상대수학",
        "Real Analysis": "실해석학",
        "Complex Analysis": "복소해석학",
        "Numerical Analysis": "수치해석",
        "Discrete Mathematics": "이산수학",
        "Graph Theory": "그래프 이론",
        "Combinatorics": "조합론",
        "Permutation": "순열",
        "Combination": "조합",
        "Binomial Theorem": "이항정리",
        "Mathematical Induction": "수학적 귀납법",
        "Axiom": "공리",
        "Lemma": "보조 정리",
        "Corollary": "따름 정리",
        "Conjecture": "추측",
        "Counterexample": "반례",
        "Function": "함수",
        "Domain": "정의역",
        "Range": "치역",
        "Bijection": "전단사 함수",
        "Injection": "단사 함수",
        "Surjection": "전사 함수",
        "Inverse Function": "역함수",
        "Composition": "합성 함수",
        "Sequence": "수열",
        "Series": "급수",
        "Taylor Series": "테일러 급수",
        "Fourier Series": "푸리에 급수",
        "Vector": "벡터",
        "Vector Space": "벡터 공간",
        "Basis": "기저",
        "Dimension": "차원",
        "Linear Independence": "선형 독립",
        "Span": "생성",
        "Subspace": "부분 공간",
        "Inner Product": "내적",
        "Norm": "노름",
        "Orthogonality": "직교성",
        "Gram-Schmidt Process": "그람-슈미트 과정",
        "Determinant": "행렬식",
        "Inverse Matrix": "역행렬",
        "Transpose": "전치행렬",
        "Rank": "계수",
        "Null Space": "영공간",
        "Linear Transformation": "선형 변환",
        "Partial Derivative": "편미분",
        "Gradient": "기울기",
        "Divergence Theorem": "발산 정리",
        "Stokes' Theorem": "스토크스 정리",
        "Green's Theorem": "그린 정리",
        "Lagrange Multiplier": "라그랑주 승수",
        "Optimization": "최적화",
        "Convexity": "볼록성",
        "Group": "군",
        "Ring": "환",
        "Field": "체",
        "Homomorphism": "준동형사상",
        "Isomorphism": "동형사상",
        "Quotient Group": "몫군",
        "Normal Subgroup": "정규 부분군",
        "Metric Space": "거리 공간",
        "Open Set": "열린 집합",
        "Closed Set": "닫힌 집합",
        "Compactness": "컴팩트성",
        "Connectedness": "연결성",
        "Homeomorphism": "위상 동형",
        "Measure Theory": "측도론",
        "Lebesgue Integral": "르베그 적분",
        "Probability Distribution": "확률 분포",
        "Random Variable": "확률 변수",
        "Expected Value": "기댓값",
        "Standard Deviation": "표준편차",
        "Normal Distribution": "정규 분포",
        "Central Limit Theorem": "중심 극한 정리",
        "Hypothesis Testing": "가설 검정",
        "P-value": "p-값",
        "Confidence Interval": "신뢰 구간",
        "Regression Analysis": "회귀 분석",
        "Bayesian Statistics": "베이즈 통계",
        "Stochastic Process": "확률 과정",
        "Markov Chain": "마르코프 연쇄",
    },

    "Physics": {
        "Mechanics": "역학",
        "Electromagnetism": "전자기학",
        "Quantum Mechanics": "양자역학",
        "Relativity": "상대성 이론",
        "Thermodynamics": "열역학",
        "Wave": "파동",
        "Optics": "광학",
        "Nuclear Physics": "핵물리학",
        "Particle Physics": "입자물리학",
        "Momentum": "운동량",
        "Velocity": "속도",
        "Acceleration": "가속도",
        "Force": "힘",
        "Energy": "에너지",
        "Work": "일",
        "Power": "일률",
        "Entropy": "엔트로피",
        "Photon": "광자",
        "Electron": "전자",
        "Gravity": "중력",
        "Newton's First Law": "뉴턴 제1법칙(관성의 법칙)",
        "Newton's Second Law": "뉴턴 제2법칙(가속도의 법칙)",
        "Newton's Third Law": "뉴턴 제3법칙(작용·반작용의 법칙)",
        "Conservation of Momentum": "운동량 보존 법칙",
        "Conservation of Energy": "에너지 보존 법칙",
        "Friction": "마찰력",
        "Normal Force": "수직 항력",
        "Tension": "장력",
        "Centripetal Force": "구심력",
        "Angular Momentum": "각운동량",
        "Torque": "돌림힘",
        "Moment of Inertia": "관성 모멘트",
        "Simple Harmonic Motion": "단순 조화 운동",
        "Pendulum": "진자",
        "Spring": "용수철",
        "Hooke's Law": "훅의 법칙",
        "Pressure": "압력",
        "Buoyancy": "부력",
        "Archimedes' Principle": "아르키메데스의 원리",
        "Bernoulli's Principle": "베르누이 원리",
        "Temperature": "온도",
        "Heat": "열",
        "Specific Heat": "비열",
        "Thermal Expansion": "열팽창",
        "Ideal Gas Law": "이상 기체 법칙",
        "Boltzmann Constant": "볼츠만 상수",
        "Electric Charge": "전하",
        "Electric Field": "전기장",
        "Electric Potential": "전위",
        "Coulomb's Law": "쿨롱의 법칙",
        "Magnetic Field": "자기장",
        "Magnetic Force": "자기력",
        "Faraday's Law": "패러데이 법칙",
        "Electromagnetic Induction": "전자기 유도",
        "Maxwell's Equations": "맥스웰 방정식",
        "Speed of Light": "빛의 속도",
        "Refraction": "굴절",
        "Reflection": "반사",
        "Diffraction": "회절",
        "Interference": "간섭",
        "Polarization": "편광",
        "Lens": "렌즈",
        "Wavelength": "파장",
        "Frequency": "진동수",
        "Amplitude": "진폭",
        "Doppler Effect": "도플러 효과",
        "Wave-particle Duality": "파동-입자 이중성",
        "Uncertainty Principle": "불확정성 원리",
        "Wave Function": "파동 함수",
        "Schrödinger Equation": "슈뢰딩거 방정식",
        "Quantum State": "양자 상태",
        "Superposition": "중첩",
        "Quantum Entanglement": "양자 얽힘",
        "Spin": "스핀",
        "Pauli Exclusion Principle": "파울리 배타 원리",
        "Special Relativity": "특수 상대성 이론",
        "General Relativity": "일반 상대성 이론",
        "Time Dilation": "시간 팽창",
        "Length Contraction": "길이 수축",
        "Mass-Energy Equivalence": "질량-에너지 등가",
        "Black Hole": "블랙홀",
        "Dark Matter": "암흑 물질",
        "Dark Energy": "암흑 에너지",
        "Big Bang": "빅뱅",
        "Cosmic Microwave Background": "우주 마이크로파 배경",
        "Nuclear Fission": "핵분열",
        "Nuclear Fusion": "핵융합",
        "Radioactive Decay": "방사성 붕괴",
        "Half-life": "반감기",
        "Standard Model": "표준 모형",
        "Quark": "쿼크",
        "Lepton": "렙톤",
        "Boson": "보손",
        "Higgs Field": "힉스 장",
        "Strong Force": "강한 핵력",
        "Weak Force": "약한 핵력",
        "Plasma": "플라즈마",
        "Superconductivity": "초전도성",
        "Condensed Matter Physics": "응집 물질 물리학",
        "Astrophysics": "천체물리학",
    },

    "Medical": {
        "Anatomy": "해부학",
        "Physiology": "생리학",
        "Pathology": "병리학",
        "Pharmacology": "약리학",
        "Diagnosis": "진단",
        "Prognosis": "예후",
        "Etiology": "병인론",
        "Symptom": "증상",
        "Sign": "징후",
        "Treatment": "치료",
        "Inflammation": "염증",
        "Infection": "감염",
        "Immunity": "면역",
        "Cardiac": "심장의",
        "Pulmonary": "폐의",
        "Renal": "신장의",
        "Hepatic": "간의",
        "Neurological": "신경학적",
        "Surgical": "외과적",
        "Clinical Trial": "임상 시험",
        "Biopsy": "생검",
        "MRI": "자기공명영상",
        "CT Scan": "컴퓨터 단층촬영",
        "Hypertension": "고혈압",
        "Diabetes Mellitus": "당뇨병",
        "Cardiovascular Disease": "심혈관 질환",
        "Myocardial Infarction": "심근경색",
        "Stroke": "뇌졸중",
        "Arrhythmia": "부정맥",
        "Heart Failure": "심부전",
        "Atherosclerosis": "동맥경화",
        "Thrombosis": "혈전증",
        "Embolism": "색전증",
        "Pneumonia": "폐렴",
        "Tuberculosis": "결핵",
        "Asthma": "천식",
        "COPD": "만성 폐쇄성 폐질환",
        "Chronic Kidney Disease": "만성 신장 질환",
        "Liver Cirrhosis": "간경변",
        "Hepatitis": "간염",
        "Gastroenteritis": "위장염",
        "Peptic Ulcer": "소화성 궤양",
        "Appendicitis": "맹장염",
        "Anemia": "빈혈",
        "Leukemia": "백혈병",
        "Lymphoma": "림프종",
        "Metastasis": "전이",
        "Tumor": "종양",
        "Benign": "양성",
        "Malignant": "악성",
        "Chemotherapy": "화학 요법",
        "Radiation Therapy": "방사선 치료",
        "Immunotherapy": "면역 치료",
        "Surgery": "수술",
        "Anesthesia": "마취",
        "Antibiotic": "항생제",
        "Antiviral": "항바이러스제",
        "Vaccine": "백신",
        "Prophylaxis": "예방",
        "Screening": "선별 검사",
        "Blood Test": "혈액 검사",
        "Urinalysis": "소변 검사",
        "ECG": "심전도",
        "Ultrasound": "초음파",
        "X-ray": "엑스레이",
        "Endoscopy": "내시경",
        "Lumbar Puncture": "요추 천자",
        "Intravenous": "정맥 내",
        "Intramuscular": "근육 내",
        "Subcutaneous": "피하",
        "Dosage": "용량",
        "Side Effect": "부작용",
        "Contraindication": "금기",
        "Allergy": "알레르기",
        "Autoimmune": "자가면역",
        "Systemic Lupus Erythematosus": "전신 홍반 루푸스",
        "Rheumatoid Arthritis": "류마티스 관절염",
        "Osteoporosis": "골다공증",
        "Epilepsy": "뇌전증",
        "Parkinson's Disease": "파킨슨병",
        "Alzheimer's Disease": "알츠하이머병",
        "Dementia": "치매",
        "Depression": "우울증",
        "Anxiety Disorder": "불안 장애",
        "Schizophrenia": "조현병",
        "Hypothyroidism": "갑상선 기능 저하증",
        "Hyperthyroidism": "갑상선 기능 항진증",
        "Sepsis": "패혈증",
        "Shock": "쇼크",
        "Evidence-Based Medicine": "근거 중심 의학",
        "Informed Consent": "사전 동의",
        "Medical Ethics": "의료 윤리",
        "Palliative Care": "완화 치료",
        "Telemedicine": "원격 의료",
        "Genomic Medicine": "유전체 의학",
        "Precision Medicine": "정밀 의학",
        "Biomarker": "생체 표지자",
        "Chronic Disease": "만성 질환",
        "Acute Disease": "급성 질환",
        "Comorbidity": "동반 질환",
    },

    "Nursing": {
        "Assessment": "사정",
        "Diagnosis": "진단",
        "Planning": "계획",
        "Implementation": "수행",
        "Evaluation": "평가",
        "Intervention": "중재",
        "Outcome": "결과",
        "Vital Signs": "활력 징후",
        "Blood Pressure": "혈압",
        "Pulse": "맥박",
        "Respiration": "호흡",
        "Temperature": "체온",
        "Oxygen Saturation": "산소 포화도",
        "Medication": "투약",
        "Intravenous": "정맥 내",
        "Catheter": "카테터",
        "Wound Care": "상처 간호",
        "Infection Control": "감염 관리",
        "Aseptic Technique": "무균술",
        "Patient Safety": "환자 안전",
        "Documentation": "기록",
        "Informed Consent": "사전 동의",
        "Ethics": "윤리",
        "Holistic Care": "전인 간호",
        "Evidence-Based Practice": "근거 중심 실무",
        "Nursing Process": "간호 과정",
        "Subjective Data": "주관적 자료",
        "Objective Data": "객관적 자료",
        "Nursing Diagnosis": "간호 진단",
        "NANDA": "북미 간호 진단 협회",
        "NIC": "간호 중재 분류",
        "NOC": "간호 결과 분류",
        "SOAP Note": "SOAP 기록",
        "Auscultation": "청진",
        "Percussion": "타진",
        "Palpation": "촉진",
        "Inspection": "시진",
        "Pain Scale": "통증 척도",
        "Glasgow Coma Scale": "글래스고 혼수 척도",
        "Fall Risk Assessment": "낙상 위험 사정",
        "Pressure Ulcer": "압박 궤양",
        "Braden Scale": "브레이든 척도",
        "Fluid Balance": "수액 균형",
        "Intake and Output": "섭취량 및 배설량",
        "Nasogastric Tube": "비위관",
        "Foley Catheter": "폴리 카테터",
        "Tracheostomy": "기관절개술",
        "Suctioning": "흡인",
        "Oxygen Therapy": "산소 요법",
        "Nebulizer": "분무기",
        "Blood Glucose Monitoring": "혈당 모니터링",
        "Insulin Administration": "인슐린 투여",
        "Central Venous Line": "중심 정맥관",
        "Peripheral IV": "말초 정맥관",
        "Transfusion": "수혈",
        "Pharmacokinetics": "약동학",
        "Drug Interaction": "약물 상호작용",
        "Adverse Effect": "이상 반응",
        "Five Rights": "투약 5원칙",
        "Scope of Practice": "업무 범위",
        "Delegation": "업무 위임",
        "Critical Thinking": "비판적 사고",
        "Clinical Judgment": "임상적 판단",
        "Triage": "중증도 분류",
        "Emergency Care": "응급 간호",
        "CPR": "심폐소생술",
        "AED": "자동 제세동기",
        "Post-operative Care": "수술 후 간호",
        "Pre-operative Care": "수술 전 간호",
        "Palliative Care": "완화 간호",
        "End-of-Life Care": "임종 간호",
        "Discharge Planning": "퇴원 계획",
        "Patient Education": "환자 교육",
        "Community Health": "지역사회 간호",
        "Maternal Nursing": "모성 간호",
        "Pediatric Nursing": "아동 간호",
        "Geriatric Nursing": "노인 간호",
        "Psychiatric Nursing": "정신 간호",
        "Rehabilitation Nursing": "재활 간호",
        "Therapeutic Communication": "치료적 의사소통",
        "Empathy": "공감",
        "Cultural Competence": "문화적 역량",
        "Health Promotion": "건강 증진",
        "Disease Prevention": "질병 예방",
        "Risk Factor": "위험 요인",
        "Standard Precaution": "표준 주의",
        "Hand Hygiene": "손 위생",
        "PPE": "개인 보호 장비",
        "Isolation": "격리",
        "Sterilization": "멸균",
        "Disinfection": "소독",
        "Chain of Infection": "감염 연쇄",
        "Nosocomial Infection": "병원 감염",
        "Medication Reconciliation": "약물 조정",
        "Incident Report": "사고 보고서",
        "Quality Improvement": "질 향상",
        "Nursing Informatics": "간호 정보학",
        "Telehealth Nursing": "원격 간호",
        "Simulation-based Learning": "시뮬레이션 기반 학습",
        "Interdisciplinary Collaboration": "다학제적 협력",
    },

    "Architecture": {
        "Structural Analysis": "구조 해석",
        "Blueprint": "설계 도면",
        "Load Bearing": "하중 지지",
        "Foundation": "기초",
        "Beam": "보",
        "Column": "기둥",
        "Facade": "파사드(건물 외벽)",
        "Urban Planning": "도시 계획",
        "Zoning": "용도 지역",
        "Sustainability": "지속 가능성",
        "Green Building": "친환경 건물",
        "HVAC": "냉난방 및 환기 시스템",
        "Acoustics": "음향학",
        "Aesthetics": "미학",
        "Rendering": "렌더링",
        "BIM": "건물 정보 모델링",
        "Construction": "시공",
        "Renovation": "리노베이션",
        "Interior": "실내",
        "Exterior": "외부",
        "Site Analysis": "대지 분석",
        "Floor Plan": "평면도",
        "Elevation": "입면도",
        "Section": "단면도",
        "Isometric Drawing": "등축 투영도",
        "Scale Model": "축척 모형",
        "Massing": "매싱(건물 덩어리)",
        "Proportion": "비례",
        "Symmetry": "대칭",
        "Rhythm": "리듬",
        "Axis": "축",
        "Circulation": "동선",
        "Program": "프로그램(공간 계획)",
        "Spatial Sequence": "공간 시퀀스",
        "Fenestration": "창문 배치",
        "Skylight": "천창",
        "Cantilever": "캔틸레버",
        "Arch": "아치",
        "Vault": "볼트",
        "Dome": "돔",
        "Truss": "트러스",
        "Shear Wall": "전단벽",
        "Retaining Wall": "옹벽",
        "Pile Foundation": "말뚝 기초",
        "Mat Foundation": "매트 기초",
        "Curtain Wall": "커튼월",
        "Cladding": "외장재",
        "Insulation": "단열",
        "Waterproofing": "방수",
        "Roofing": "지붕 시공",
        "Concrete": "콘크리트",
        "Steel": "철골",
        "Timber": "목재",
        "Masonry": "조적",
        "Glass": "유리",
        "Mixed Use": "복합 용도",
        "Adaptive Reuse": "용도 전환",
        "Prefabrication": "조립식 공법",
        "Modular Design": "모듈 설계",
        "Parametric Design": "파라메트릭 설계",
        "Computational Design": "컴퓨테이셔널 디자인",
        "3D Modeling": "3D 모델링",
        "Virtual Reality": "가상현실",
        "Augmented Reality": "증강현실",
        "LEED Certification": "LEED 인증",
        "Passive Design": "패시브 설계",
        "Daylighting": "자연 채광",
        "Thermal Mass": "열 질량",
        "Vernacular Architecture": "지역 건축",
        "Modernism": "모더니즘",
        "Postmodernism": "포스트모더니즘",
        "Deconstructivism": "해체주의",
        "Minimalism": "미니멀리즘",
        "Contextualism": "맥락주의",
        "Fenestration Ratio": "창면적비",
        "Floor Area Ratio": "용적률",
        "Building Coverage Ratio": "건폐율",
        "Setback": "건축 한계선",
        "Right of Way": "도로 공간",
        "Landscape Architecture": "조경",
        "Hardscape": "포장 조경",
        "Softscape": "식재 조경",
        "Universal Design": "유니버설 디자인",
        "Accessibility": "접근성",
        "Egress": "피난 동선",
        "Fire Resistance": "내화성",
        "Building Code": "건축 법규",
        "Permit": "허가",
        "Construction Document": "시공 도서",
        "Specification": "시방서",
        "Bill of Quantities": "물량 내역서",
        "Cost Estimation": "공사비 산정",
        "Project Management": "프로젝트 관리",
        "Design-Build": "설계 시공 일괄",
        "Feasibility Study": "타당성 조사",
        "Structural Engineer": "구조 기술자",
        "MEP": "기계·전기·배관",
        "Passive House": "패시브 하우스",
        "Net Zero Building": "넷제로 건물",
        "Biophilic Design": "생물 친화적 설계",
    },

    # ─────────────────────────────────────────
    # 문과 (Humanities)
    # ─────────────────────────────────────────

    "Business Administration": {
        "Asset": "자산",
        "Liability": "부채",
        "Equity": "자본",
        "Revenue": "매출",
        "Profit": "이익",
        "Net Income": "순이익",
        "Cash Flow": "현금 흐름",
        "Balance Sheet": "대차대조표",
        "Income Statement": "손익계산서",
        "ROI": "투자 수익률",
        "KPI": "핵심 성과 지표",
        "Supply Chain": "공급망",
        "Stakeholder": "이해관계자",
        "Corporate Governance": "기업 지배구조",
        "Merger": "합병",
        "Acquisition": "인수",
        "Strategic Planning": "전략 기획",
        "SWOT Analysis": "SWOT 분석",
        "Market Share": "시장 점유율",
        "Competitive Advantage": "경쟁 우위",
        "Outsourcing": "외주",
        "Entrepreneurship": "기업가 정신",
        "Venture Capital": "벤처 캐피털",
        "Budget": "예산",
        "Forecast": "예측",
        "Organizational Structure": "조직 구조",
        "Corporate Culture": "기업 문화",
        "Human Resource Management": "인적 자원 관리",
        "Recruitment": "채용",
        "Talent Management": "인재 관리",
        "Performance Appraisal": "성과 평가",
        "Compensation": "보상",
        "Employee Engagement": "직원 몰입도",
        "Leadership": "리더십",
        "Management Style": "관리 스타일",
        "Delegation": "위임",
        "Empowerment": "권한 부여",
        "Change Management": "변화 관리",
        "Innovation": "혁신",
        "Business Model": "비즈니스 모델",
        "Value Chain": "가치 사슬",
        "Porter's Five Forces": "포터의 5가지 경쟁 요인",
        "Blue Ocean Strategy": "블루오션 전략",
        "Core Competency": "핵심 역량",
        "Diversification": "다각화",
        "Vertical Integration": "수직적 통합",
        "Horizontal Integration": "수평적 통합",
        "Joint Venture": "합작 투자",
        "Strategic Alliance": "전략적 제휴",
        "Franchise": "프랜차이즈",
        "Intellectual Property": "지적 재산",
        "Brand Management": "브랜드 관리",
        "Customer Relationship Management": "고객 관계 관리",
        "Enterprise Resource Planning": "전사적 자원 관리",
        "Business Intelligence": "비즈니스 인텔리전스",
        "Operations Management": "운영 관리",
        "Project Management": "프로젝트 관리",
        "Risk Management": "위험 관리",
        "Compliance": "법규 준수",
        "Corporate Social Responsibility": "기업의 사회적 책임",
        "ESG": "ESG(환경·사회·지배구조)",
        "Sustainability": "지속 가능성",
        "Stakeholder Theory": "이해관계자 이론",
        "Agency Theory": "대리인 이론",
        "Transaction Cost": "거래 비용",
        "Economies of Scale": "규모의 경제",
        "Economies of Scope": "범위의 경제",
        "Break-even Point": "손익분기점",
        "Fixed Cost": "고정 비용",
        "Variable Cost": "변동 비용",
        "Marginal Cost": "한계 비용",
        "Profit Margin": "이익률",
        "Gross Profit": "매출 총이익",
        "EBITDA": "EBITDA(세전 이자·세금·감가상각 전 이익)",
        "Working Capital": "운전 자본",
        "Accounts Receivable": "매출 채권",
        "Accounts Payable": "매입 채무",
        "Inventory Management": "재고 관리",
        "Just-in-Time": "적시 생산 방식",
        "Total Quality Management": "전사적 품질 관리",
        "Benchmarking": "벤치마킹",
        "Market Penetration": "시장 침투",
        "Market Development": "시장 개발",
        "Product Development": "제품 개발",
        "Ansoff Matrix": "앤소프 매트릭스",
        "BCG Matrix": "BCG 매트릭스",
        "GE-McKinsey Matrix": "GE-맥킨지 매트릭스",
        "Balanced Scorecard": "균형 성과표",
        "OKR": "OKR(목표 및 핵심 결과)",
        "Lean Startup": "린 스타트업",
        "Minimum Viable Product": "최소 기능 제품",
        "Pivot": "피벗",
        "Scalability": "확장성",
        "Exit Strategy": "출구 전략",
        "IPO": "기업 공개",
        "Private Equity": "사모 펀드",
        "Due Diligence": "실사",
        "Organizational Behavior": "조직 행동론",
        "Negotiation": "협상",
        "Conflict Management": "갈등 관리",
    },

    "Economics": {
        "Supply": "공급",
        "Demand": "수요",
        "Equilibrium": "균형",
        "Elasticity": "탄력성",
        "Inflation": "인플레이션",
        "Deflation": "디플레이션",
        "GDP": "국내총생산",
        "GNP": "국민총생산",
        "Unemployment": "실업",
        "Fiscal Policy": "재정 정책",
        "Monetary Policy": "통화 정책",
        "Interest Rate": "금리",
        "Exchange Rate": "환율",
        "Trade Balance": "무역 수지",
        "Tariff": "관세",
        "Subsidy": "보조금",
        "Monopoly": "독점",
        "Oligopoly": "과점",
        "Perfect Competition": "완전 경쟁",
        "Market Failure": "시장 실패",
        "Externality": "외부 효과",
        "Public Good": "공공재",
        "Opportunity Cost": "기회 비용",
        "Marginal Cost": "한계 비용",
        "Consumer Surplus": "소비자 잉여",
        "Producer Surplus": "생산자 잉여",
        "Deadweight Loss": "자중 손실",
        "Price Ceiling": "가격 상한제",
        "Price Floor": "가격 하한제",
        "Comparative Advantage": "비교 우위",
        "Absolute Advantage": "절대 우위",
        "Terms of Trade": "교역 조건",
        "Current Account": "경상 수지",
        "Capital Account": "자본 수지",
        "Balance of Payments": "국제 수지",
        "Foreign Direct Investment": "외국인 직접 투자",
        "Portfolio Investment": "포트폴리오 투자",
        "Purchasing Power Parity": "구매력 평가",
        "Money Supply": "통화량",
        "Quantitative Easing": "양적 완화",
        "Reserve Requirement": "지급 준비율",
        "Central Bank": "중앙은행",
        "Open Market Operation": "공개 시장 조작",
        "Bond": "채권",
        "Yield": "수익률",
        "Stock Market": "주식 시장",
        "Asset Bubble": "자산 버블",
        "Financial Crisis": "금융 위기",
        "Recession": "경기 침체",
        "Depression": "경제 공황",
        "Business Cycle": "경기 순환",
        "Leading Indicator": "선행 지표",
        "Lagging Indicator": "후행 지표",
        "Consumer Price Index": "소비자 물가 지수",
        "Producer Price Index": "생산자 물가 지수",
        "Human Development Index": "인간 개발 지수",
        "Gini Coefficient": "지니 계수",
        "Income Distribution": "소득 분배",
        "Poverty Trap": "빈곤의 덫",
        "Microeconomics": "미시경제학",
        "Macroeconomics": "거시경제학",
        "Behavioral Economics": "행동경제학",
        "Game Theory": "게임 이론",
        "Nash Equilibrium": "내시 균형",
        "Prisoner's Dilemma": "죄수의 딜레마",
        "Moral Hazard": "도덕적 해이",
        "Adverse Selection": "역선택",
        "Information Asymmetry": "정보 비대칭",
        "Rational Expectations": "합리적 기대",
        "Keynesian Economics": "케인즈 경제학",
        "Monetarism": "통화주의",
        "Supply-side Economics": "공급 측 경제학",
        "Laffer Curve": "래퍼 곡선",
        "Phillips Curve": "필립스 곡선",
        "IS-LM Model": "IS-LM 모형",
        "Aggregate Demand": "총수요",
        "Aggregate Supply": "총공급",
        "Multiplier Effect": "승수 효과",
        "Crowding Out": "구축 효과",
        "Stagflation": "스태그플레이션",
        "Hyperinflation": "초인플레이션",
        "Globalization": "세계화",
        "Free Trade Agreement": "자유 무역 협정",
        "World Trade Organization": "세계 무역 기구",
        "International Monetary Fund": "국제 통화 기금",
        "World Bank": "세계 은행",
        "Austerity": "긴축 재정",
        "Sovereign Debt": "국가 부채",
        "Credit Rating": "신용 등급",
        "Default": "채무 불이행",
        "Derivatives": "파생 상품",
        "Hedge Fund": "헤지 펀드",
        "Cryptocurrency": "암호 화폐",
        "Digital Economy": "디지털 경제",
        "Platform Economy": "플랫폼 경제",
        "Sharing Economy": "공유 경제",
        "Green Economy": "녹색 경제",
        "Inequality of Wealth": "부의 불평등",
        "Labor Market": "노동 시장",
        "Minimum Wage": "최저 임금",
    },

    "Marketing": {
        "Brand": "브랜드",
        "Target Market": "목표 시장",
        "Market Segmentation": "시장 세분화",
        "Positioning": "포지셔닝",
        "Consumer Behavior": "소비자 행동",
        "Marketing Mix": "마케팅 믹스",
        "Product": "제품",
        "Price": "가격",
        "Place": "유통",
        "Promotion": "촉진",
        "Advertising": "광고",
        "Digital Marketing": "디지털 마케팅",
        "Social Media": "소셜 미디어",
        "Content Marketing": "콘텐츠 마케팅",
        "SEO": "검색 엔진 최적화",
        "Customer Loyalty": "고객 충성도",
        "Customer Retention": "고객 유지",
        "Sales Funnel": "판매 깔때기",
        "Lead Generation": "리드 생성",
        "Conversion Rate": "전환율",
        "ROI": "투자 수익률",
        "Brand Equity": "브랜드 자산",
        "Value Proposition": "가치 제안",
        "AIDA Model": "AIDA 모델(주의-관심-욕구-행동)",
        "Market Research": "시장 조사",
        "Buyer Persona": "구매자 페르소나",
        "Customer Journey": "고객 여정",
        "Touchpoint": "접점",
        "Omnichannel": "옴니채널",
        "Customer Lifetime Value": "고객 생애 가치",
        "Churn Rate": "이탈률",
        "Net Promoter Score": "순 추천 지수",
        "Brand Awareness": "브랜드 인지도",
        "Brand Image": "브랜드 이미지",
        "Brand Loyalty": "브랜드 충성도",
        "Rebranding": "리브랜딩",
        "Co-branding": "공동 브랜딩",
        "Product Lifecycle": "제품 수명 주기",
        "Market Introduction": "시장 도입",
        "Market Growth": "시장 성장",
        "Market Maturity": "시장 성숙",
        "Market Decline": "시장 쇠퇴",
        "New Product Development": "신제품 개발",
        "Product Differentiation": "제품 차별화",
        "Competitive Analysis": "경쟁사 분석",
        "PEST Analysis": "PEST 분석",
        "Pricing Strategy": "가격 전략",
        "Penetration Pricing": "침투 가격",
        "Skimming Pricing": "스키밍 가격",
        "Dynamic Pricing": "동적 가격",
        "Freemium": "프리미엄 모델",
        "Subscription Model": "구독 모델",
        "Distribution Channel": "유통 채널",
        "Retailer": "소매업자",
        "Wholesaler": "도매업자",
        "E-commerce": "전자상거래",
        "Direct-to-Consumer": "직접 판매",
        "Push Strategy": "푸시 전략",
        "Pull Strategy": "풀 전략",
        "IMC": "통합 마케팅 커뮤니케이션",
        "Public Relations": "홍보",
        "Influencer Marketing": "인플루언서 마케팅",
        "Affiliate Marketing": "제휴 마케팅",
        "Email Marketing": "이메일 마케팅",
        "Mobile Marketing": "모바일 마케팅",
        "Programmatic Advertising": "프로그래매틱 광고",
        "Retargeting": "리타겟팅",
        "A/B Testing": "A/B 테스트",
        "Marketing Analytics": "마케팅 분석",
        "KPI": "핵심 성과 지표",
        "Impression": "노출 수",
        "Click-through Rate": "클릭률",
        "Bounce Rate": "이탈률",
        "Engagement Rate": "참여율",
        "Viral Marketing": "바이럴 마케팅",
        "Word of Mouth": "구전 마케팅",
        "Guerrilla Marketing": "게릴라 마케팅",
        "Experiential Marketing": "체험 마케팅",
        "Neuromarketing": "뉴로마케팅",
        "Cause Marketing": "공익 연계 마케팅",
        "Sustainability Marketing": "지속 가능성 마케팅",
        "Data-Driven Marketing": "데이터 기반 마케팅",
        "Marketing Automation": "마케팅 자동화",
        "CRM": "고객 관계 관리",
        "Segmentation Variable": "세분화 변수",
        "Psychographic": "심리 특성",
        "Demographics": "인구 통계",
        "Geographics": "지리적 특성",
        "Behavioral Segmentation": "행동적 세분화",
        "Focus Group": "포커스 그룹",
        "Survey": "설문 조사",
        "Ethnographic Research": "민족지학적 조사",
        "Conjoint Analysis": "컨조인트 분석",
        "Brand Extension": "브랜드 확장",
        "Cross-selling": "교차 판매",
        "Up-selling": "상향 판매",
        "Loss Leader": "손실 유도 제품",
        "Brand Ambassador": "브랜드 홍보대사",
        "Sponsorship": "스폰서십",
        "Event Marketing": "이벤트 마케팅",
    },

    "Accounting": {
        "Debit": "차변",
        "Credit": "대변",
        "Journal Entry": "분개",
        "Ledger": "원장",
        "Trial Balance": "시산표",
        "Balance Sheet": "대차대조표",
        "Income Statement": "손익계산서",
        "Cash Flow Statement": "현금흐름표",
        "Depreciation": "감가상각",
        "Amortization": "상각",
        "Audit": "감사",
        "GAAP": "일반회계기준",
        "IFRS": "국제회계기준",
        "Accrual": "발생주의",
        "Asset": "자산",
        "Liability": "부채",
        "Equity": "자본",
        "Revenue": "수익",
        "Expense": "비용",
        "Tax": "세금",
        "Inventory": "재고",
        "Accounts Receivable": "매출채권",
        "Accounts Payable": "매입채무",
        "Payroll": "급여",
        "Cost Accounting": "원가회계",
        "Current Asset": "유동 자산",
        "Non-current Asset": "비유동 자산",
        "Current Liability": "유동 부채",
        "Long-term Liability": "장기 부채",
        "Retained Earnings": "이익 잉여금",
        "Paid-in Capital": "납입 자본금",
        "Treasury Stock": "자기 주식",
        "Dividend": "배당금",
        "Earnings Per Share": "주당 순이익",
        "Price-to-Earnings Ratio": "주가수익비율",
        "Book Value": "장부 가액",
        "Fair Value": "공정 가치",
        "Historical Cost": "역사적 원가",
        "Carrying Amount": "장부 금액",
        "Impairment": "손상차손",
        "Goodwill": "영업권",
        "Intangible Asset": "무형 자산",
        "Tangible Asset": "유형 자산",
        "Fixed Asset": "고정 자산",
        "Capital Expenditure": "자본적 지출",
        "Operating Expenditure": "운영 비용",
        "Gross Profit": "매출 총이익",
        "Operating Income": "영업 이익",
        "Net Profit": "순이익",
        "EBITDA": "EBITDA",
        "Working Capital": "운전 자본",
        "Liquidity": "유동성",
        "Solvency": "지급 능력",
        "Current Ratio": "유동 비율",
        "Quick Ratio": "당좌 비율",
        "Debt-to-Equity Ratio": "부채비율",
        "Return on Equity": "자기자본이익률",
        "Return on Assets": "자산수익률",
        "Gross Margin": "매출 총이익률",
        "Net Margin": "순이익률",
        "Asset Turnover": "자산 회전율",
        "Inventory Turnover": "재고 회전율",
        "Receivables Turnover": "매출채권 회전율",
        "Break-even Analysis": "손익분기점 분석",
        "Variance Analysis": "차이 분석",
        "Standard Cost": "표준 원가",
        "Activity-Based Costing": "활동 기준 원가 계산",
        "Marginal Costing": "한계 원가 계산",
        "Absorption Costing": "전부 원가 계산",
        "Transfer Pricing": "이전 가격",
        "Consolidation": "연결 재무제표",
        "Subsidiary": "자회사",
        "Minority Interest": "소수 주주 지분",
        "Foreign Currency Translation": "외화 환산",
        "Hedge Accounting": "헤지 회계",
        "Lease Accounting": "리스 회계",
        "Revenue Recognition": "수익 인식",
        "Matching Principle": "대응 원칙",
        "Conservatism": "보수주의",
        "Materiality": "중요성",
        "Going Concern": "계속 기업 가정",
        "Internal Control": "내부 통제",
        "Fraud": "사기",
        "Forensic Accounting": "법정 회계",
        "Tax Planning": "세금 계획",
        "Deferred Tax": "이연 법인세",
        "Value Added Tax": "부가가치세",
        "Corporate Tax": "법인세",
        "Withholding Tax": "원천징수세",
        "Double-entry Bookkeeping": "복식 부기",
        "Chart of Accounts": "계정 과목표",
        "Reconciliation": "조정",
        "Bank Statement": "은행 명세서",
        "Petty Cash": "소액 현금",
        "Imprest System": "정액 보충 제도",
        "Management Accounting": "관리 회계",
        "Financial Accounting": "재무 회계",
        "Public Accounting": "공공 회계",
        "Bookkeeping": "장부 기장",
        "Accounting Period": "회계 기간",
    },

    "Psychology": {
        "Cognition": "인지",
        "Behavior": "행동",
        "Emotion": "감정",
        "Motivation": "동기",
        "Perception": "지각",
        "Memory": "기억",
        "Attention": "주의",
        "Learning": "학습",
        "Conditioning": "조건화",
        "Reinforcement": "강화",
        "Punishment": "처벌",
        "Classical Conditioning": "고전적 조건화",
        "Operant Conditioning": "조작적 조건화",
        "Cognitive Dissonance": "인지 부조화",
        "Self-efficacy": "자기효능감",
        "Personality": "성격",
        "Trait": "특성",
        "Disorder": "장애",
        "Therapy": "치료",
        "Psychotherapy": "심리치료",
        "Cognitive Behavioral Therapy": "인지행동치료",
        "Unconscious": "무의식",
        "Stress": "스트레스",
        "Coping": "대처",
        "Resilience": "회복탄력성",
        "Developmental Psychology": "발달 심리학",
        "Social Psychology": "사회 심리학",
        "Clinical Psychology": "임상 심리학",
        "Neuropsychology": "신경심리학",
        "Positive Psychology": "긍정 심리학",
        "Psychoanalysis": "정신분석",
        "Id": "이드",
        "Ego": "자아",
        "Superego": "초자아",
        "Defense Mechanism": "방어 기제",
        "Repression": "억압",
        "Projection": "투사",
        "Rationalization": "합리화",
        "Displacement": "전위",
        "Regression": "퇴행",
        "Sublimation": "승화",
        "Denial": "부정",
        "Schema": "스키마",
        "Prototype": "원형",
        "Heuristic": "휴리스틱",
        "Cognitive Bias": "인지 편향",
        "Confirmation Bias": "확증 편향",
        "Attribution Theory": "귀인 이론",
        "Fundamental Attribution Error": "근본 귀인 오류",
        "Self-serving Bias": "자기 봉사 편향",
        "Social Loafing": "사회적 태만",
        "Groupthink": "집단 사고",
        "Conformity": "동조",
        "Obedience": "복종",
        "Attitude": "태도",
        "Persuasion": "설득",
        "Stereotyping": "고정 관념",
        "Prejudice": "편견",
        "Discrimination": "차별",
        "Empathy": "공감",
        "Altruism": "이타주의",
        "Aggression": "공격성",
        "Attachment": "애착",
        "Secure Attachment": "안정 애착",
        "Avoidant Attachment": "회피 애착",
        "Sensory Memory": "감각 기억",
        "Short-term Memory": "단기 기억",
        "Long-term Memory": "장기 기억",
        "Working Memory": "작동 기억",
        "Encoding": "부호화",
        "Retrieval": "인출",
        "Forgetting": "망각",
        "Proactive Interference": "순행 간섭",
        "Retroactive Interference": "역행 간섭",
        "Implicit Memory": "암묵 기억",
        "Explicit Memory": "외현 기억",
        "Intelligence": "지능",
        "IQ": "지능 지수",
        "Multiple Intelligences": "다중 지능",
        "Emotional Intelligence": "감성 지능",
        "Consciousness": "의식",
        "Sleep": "수면",
        "Dream": "꿈",
        "Hypnosis": "최면",
        "Meditation": "명상",
        "Mindfulness": "마음챙김",
        "Well-being": "웰빙",
        "Happiness": "행복",
        "Maslow's Hierarchy": "매슬로의 욕구 계층",
        "Self-actualization": "자아실현",
        "Flow State": "플로 상태",
        "Locus of Control": "통제 소재",
        "Growth Mindset": "성장 마인드셋",
        "Fixed Mindset": "고정 마인드셋",
        "Neuroscience": "신경과학",
        "Synapse": "시냅스",
        "Neurotransmitter": "신경전달물질",
        "Cortisol": "코르티솔",
        "Amygdala": "편도체",
        "Prefrontal Cortex": "전전두 피질",
    },

    "International Relations": {
        "Sovereignty": "주권",
        "Diplomacy": "외교",
        "Globalization": "세계화",
        "Multilateralism": "다자주의",
        "Bilateral": "양자 간",
        "Geopolitics": "지정학",
        "Sanctions": "제재",
        "Treaty": "조약",
        "Alliance": "동맹",
        "Deterrence": "억지력",
        "Hegemony": "패권",
        "Soft Power": "소프트 파워",
        "Hard Power": "하드 파워",
        "Non-governmental Organization": "비정부 기구",
        "International Law": "국제법",
        "United Nations": "유엔",
        "Security Council": "안전보장이사회",
        "Refugee": "난민",
        "Human Rights": "인권",
        "Conflict Resolution": "분쟁 해결",
        "Realism": "현실주의",
        "Liberalism": "자유주의",
        "Constructivism": "구성주의",
        "Balance of Power": "세력 균형",
        "Security Dilemma": "안보 딜레마",
        "Nuclear Deterrence": "핵 억지",
        "Arms Control": "군비 통제",
        "Non-proliferation": "비확산",
        "Collective Security": "집단 안보",
        "Peacekeeping": "평화 유지",
        "Humanitarian Intervention": "인도주의적 개입",
        "Responsibility to Protect": "보호 책임",
        "International Trade": "국제 무역",
        "Free Trade": "자유 무역",
        "Protectionism": "보호주의",
        "Economic Sanctions": "경제 제재",
        "Foreign Policy": "외교 정책",
        "National Interest": "국가 이익",
        "State Actor": "국가 행위자",
        "Non-state Actor": "비국가 행위자",
        "Intergovernmental Organization": "정부 간 기구",
        "Regional Integration": "지역 통합",
        "European Union": "유럽 연합",
        "ASEAN": "동남아시아 국가 연합",
        "NATO": "북대서양 조약 기구",
        "World Trade Organization": "세계 무역 기구",
        "IMF": "국제 통화 기금",
        "World Bank": "세계 은행",
        "Colonialism": "식민주의",
        "Imperialism": "제국주의",
        "Post-colonialism": "탈식민주의",
        "Cold War": "냉전",
        "Bipolar System": "양극 체제",
        "Multipolar System": "다극 체제",
        "Unipolar System": "단극 체제",
        "Proxy War": "대리전",
        "Terrorism": "테러리즘",
        "Counterterrorism": "대테러리즘",
        "Asymmetric Warfare": "비대칭 전쟁",
        "Cyber Warfare": "사이버 전쟁",
        "Information Warfare": "정보전",
        "Hybrid Warfare": "하이브리드 전쟁",
        "Nuclear Weapons": "핵무기",
        "Weapons of Mass Destruction": "대량 살상 무기",
        "Climate Change Diplomacy": "기후변화 외교",
        "Paris Agreement": "파리 협정",
        "Sustainable Development Goals": "지속 가능 발전 목표",
        "Global Governance": "글로벌 거버넌스",
        "Transnational Crime": "초국가적 범죄",
        "Human Trafficking": "인신매매",
        "Drug Trafficking": "마약 밀매",
        "Migration": "이주",
        "Asylum Seeker": "망명 신청자",
        "Statelessness": "무국적",
        "Cultural Diplomacy": "문화 외교",
        "Public Diplomacy": "공공 외교",
        "Track II Diplomacy": "2트랙 외교",
        "Mediation": "조정",
        "Arbitration": "중재",
        "International Court of Justice": "국제사법재판소",
        "International Criminal Court": "국제형사재판소",
        "Genocide": "집단학살",
        "War Crimes": "전쟁 범죄",
        "Crimes Against Humanity": "반인도적 범죄",
        "Nationalism": "민족주의",
        "Ethnonationalism": "민족적 민족주의",
        "Separatism": "분리주의",
        "Irredentism": "영토 회복주의",
        "Self-determination": "자결권",
        "Democratization": "민주화",
        "Authoritarianism": "권위주의",
        "Failed State": "실패 국가",
        "Norm": "국제 규범",
        "Regime": "레짐(국제 체제)",
        "Power Transition": "세력 전이",
        "Strategic Competition": "전략적 경쟁",
        "Multilateral Diplomacy": "다자 외교",
        "Diplomatic Recognition": "외교적 승인",
        "Extraterritoriality": "치외법권",
        "Embargo": "금수 조치",
    },

    "Sociology": {
        "Social Structure": "사회 구조",
        "Social Class": "사회 계층",
        "Inequality": "불평등",
        "Norms": "규범",
        "Values": "가치",
        "Culture": "문화",
        "Socialization": "사회화",
        "Institution": "제도",
        "Deviance": "일탈",
        "Social Mobility": "사회 이동",
        "Ethnicity": "민족성",
        "Gender": "젠더",
        "Power": "권력",
        "Ideology": "이데올로기",
        "Capitalism": "자본주의",
        "Globalization": "세계화",
        "Community": "공동체",
        "Urbanization": "도시화",
        "Qualitative Research": "질적 연구",
        "Quantitative Research": "양적 연구",
        "Social Theory": "사회 이론",
        "Functionalism": "기능주의",
        "Conflict Theory": "갈등 이론",
        "Symbolic Interactionism": "상징적 상호작용론",
        "Postmodernism": "포스트모더니즘",
        "Feminism": "페미니즘",
        "Race": "인종",
        "Intersectionality": "교차성",
        "Social Capital": "사회 자본",
        "Cultural Capital": "문화 자본",
        "Habitus": "아비투스",
        "Field": "장(사회적 공간)",
        "Symbolic Violence": "상징 폭력",
        "Hegemony": "헤게모니",
        "Discourse": "담론",
        "Social Construction": "사회적 구성",
        "Agency": "행위 능력",
        "Structure": "구조",
        "Micro-sociology": "미시사회학",
        "Macro-sociology": "거시사회학",
        "Ethnography": "민족지학",
        "Participant Observation": "참여 관찰",
        "In-depth Interview": "심층 면접",
        "Survey Research": "조사 연구",
        "Content Analysis": "내용 분석",
        "Grounded Theory": "근거 이론",
        "Social Network": "사회 연결망",
        "Social Cohesion": "사회 결속",
        "Social Integration": "사회 통합",
        "Anomie": "아노미",
        "Social Control": "사회 통제",
        "Sanction": "제재",
        "Labeling Theory": "낙인 이론",
        "Stigma": "스티그마",
        "Social Movement": "사회 운동",
        "Collective Action": "집합 행동",
        "Civil Society": "시민사회",
        "Voluntary Organization": "자발적 단체",
        "Social Stratification": "사회 계층화",
        "Caste System": "카스트 제도",
        "Meritocracy": "능력주의",
        "Poverty": "빈곤",
        "Relative Deprivation": "상대적 박탈감",
        "Welfare State": "복지 국가",
        "Family": "가족",
        "Marriage": "결혼",
        "Kinship": "친족",
        "Patriarchy": "가부장제",
        "Nuclear Family": "핵가족",
        "Extended Family": "확대 가족",
        "Education System": "교육 체계",
        "Hidden Curriculum": "잠재적 교육과정",
        "Social Reproduction": "사회적 재생산",
        "Religion": "종교",
        "Secularization": "세속화",
        "Sacred and Profane": "성(聖)과 속(俗)",
        "Media": "미디어",
        "Mass Culture": "대중 문화",
        "Subculture": "하위 문화",
        "Counterculture": "대항 문화",
        "Cultural Diffusion": "문화 전파",
        "Acculturation": "문화 변용",
        "Ethnocentrism": "자문화 중심주의",
        "Cultural Relativism": "문화 상대주의",
        "Modernization": "근대화",
        "Industrialization": "산업화",
        "Post-industrial Society": "탈산업 사회",
        "Information Society": "정보 사회",
        "Network Society": "네트워크 사회",
        "Risk Society": "위험 사회",
        "Demographic Transition": "인구 전환",
        "Aging Society": "고령화 사회",
        "Migration": "이주",
        "Diaspora": "디아스포라",
        "Multiculturalism": "다문화주의",
        "Social Exclusion": "사회적 배제",
        "Social Trust": "사회적 신뢰",
        "Collective Memory": "집합 기억",
        "Social Identity": "사회적 정체성",
        "Stigma Management": "스티그마 관리",
    },

    "Media & Communication": {
        "Broadcasting": "방송",
        "Journalism": "저널리즘",
        "Media Literacy": "미디어 리터러시",
        "Framing": "프레이밍",
        "Agenda Setting": "의제 설정",
        "Public Relations": "홍보",
        "Propaganda": "선전",
        "Social Media": "소셜 미디어",
        "Audience": "수용자",
        "Content": "콘텐츠",
        "Narrative": "서사",
        "Discourse": "담론",
        "Convergence": "미디어 융합",
        "Digital Media": "디지털 미디어",
        "Censorship": "검열",
        "Freedom of Press": "언론 자유",
        "Infotainment": "인포테인먼트",
        "Fake News": "가짜 뉴스",
        "Engagement": "참여",
        "Influencer": "인플루언서",
        "Communication Theory": "커뮤니케이션 이론",
        "Encoding": "부호화",
        "Decoding": "해독",
        "Sender": "발신자",
        "Receiver": "수신자",
        "Channel": "채널",
        "Noise": "잡음",
        "Feedback": "피드백",
        "Interpersonal Communication": "대인 커뮤니케이션",
        "Mass Communication": "대중 커뮤니케이션",
        "Organizational Communication": "조직 커뮤니케이션",
        "Nonverbal Communication": "비언어적 커뮤니케이션",
        "Semiotics": "기호학",
        "Sign": "기호",
        "Signifier": "기표",
        "Signified": "기의",
        "Representation": "재현",
        "Ideology": "이데올로기",
        "Hegemony": "헤게모니",
        "Cultural Studies": "문화 연구",
        "Media Effects": "미디어 효과",
        "Cultivation Theory": "배양 이론",
        "Uses and Gratifications": "이용과 충족",
        "Two-step Flow": "2단계 흐름",
        "Gatekeeping": "게이트키핑",
        "News Value": "뉴스 가치",
        "Objectivity": "객관성",
        "Bias": "편향",
        "Spin": "스핀(정보 조작)",
        "Crisis Communication": "위기 커뮤니케이션",
        "Media Ownership": "미디어 소유",
        "Concentration": "집중화",
        "Regulation": "규제",
        "Net Neutrality": "망 중립성",
        "Algorithm": "알고리즘",
        "Filter Bubble": "필터 버블",
        "Echo Chamber": "반향실 효과",
        "Disinformation": "허위 정보",
        "Misinformation": "오정보",
        "Verification": "팩트체크",
        "Data Journalism": "데이터 저널리즘",
        "Podcast": "팟캐스트",
        "Streaming": "스트리밍",
        "User-generated Content": "사용자 제작 콘텐츠",
        "Viral Content": "바이럴 콘텐츠",
        "Transmedia": "트랜스미디어",
        "Convergence Culture": "융합 문화",
        "Participatory Culture": "참여 문화",
        "Crowdsourcing": "크라우드소싱",
        "Citizen Journalism": "시민 저널리즘",
        "Hashtag": "해시태그",
        "Trending": "트렌딩",
        "Analytics": "분석",
        "Reach": "도달",
        "Impression": "노출",
        "Share of Voice": "음성 점유율",
        "Platform": "플랫폼",
        "Algorithm-driven Media": "알고리즘 기반 미디어",
        "Attention Economy": "주의 경제",
        "Clickbait": "클릭베이트",
        "Paywall": "페이월",
        "Subscription Model": "구독 모델",
        "Media Industry": "미디어 산업",
        "Production": "제작",
        "Distribution": "배급",
        "Exhibition": "상영",
        "Copyright": "저작권",
        "Creative Commons": "크리에이티브 커먼즈",
        "Privacy": "프라이버시",
        "Surveillance": "감시",
        "Big Data": "빅데이터",
        "Personalization": "개인화",
        "Media Psychology": "미디어 심리학",
        "Health Communication": "건강 커뮤니케이션",
        "Political Communication": "정치 커뮤니케이션",
        "Intercultural Communication": "문화 간 커뮤니케이션",
        "Science Communication": "과학 커뮤니케이션",
        "Media Convergence": "미디어 수렴",
        "Mobile Journalism": "모바일 저널리즘",
        "Immersive Media": "몰입형 미디어",
    },

    "Political Science": {
        "Democracy": "민주주의",
        "Authoritarianism": "권위주의",
        "Legislature": "입법부",
        "Executive": "행정부",
        "Judiciary": "사법부",
        "Separation of Powers": "삼권분립",
        "Federalism": "연방주의",
        "Constitution": "헌법",
        "Election": "선거",
        "Voting": "투표",
        "Political Party": "정당",
        "Lobbying": "로비",
        "Policy": "정책",
        "Governance": "거버넌스",
        "Civil Society": "시민사회",
        "Bureaucracy": "관료제",
        "Totalitarianism": "전체주의",
        "Liberalism": "자유주의",
        "Conservatism": "보수주의",
        "Populism": "포퓰리즘",
        "Socialism": "사회주의",
        "Communism": "공산주의",
        "Fascism": "파시즘",
        "Anarchism": "아나키즘",
        "Nationalism": "민족주의",
        "Republicanism": "공화주의",
        "Social Democracy": "사회민주주의",
        "Neoliberalism": "신자유주의",
        "Political Ideology": "정치 이데올로기",
        "Power": "권력",
        "Legitimacy": "정당성",
        "Authority": "권위",
        "Coercion": "강제",
        "State": "국가",
        "Sovereignty": "주권",
        "Nation": "민족",
        "Citizenship": "시민권",
        "Civil Rights": "시민권",
        "Political Rights": "정치적 권리",
        "Rule of Law": "법의 지배",
        "Checks and Balances": "견제와 균형",
        "Electoral System": "선거 제도",
        "Proportional Representation": "비례대표제",
        "Majoritarian System": "다수제",
        "Gerrymandering": "선거구 획정 조작",
        "Turnout": "투표율",
        "Campaign": "선거 운동",
        "Political Participation": "정치 참여",
        "Interest Group": "이익 집단",
        "Think Tank": "싱크탱크",
        "Media and Politics": "미디어와 정치",
        "Political Socialization": "정치 사회화",
        "Political Culture": "정치 문화",
        "Public Opinion": "여론",
        "Poll": "여론 조사",
        "Agenda Setting": "의제 설정",
        "Policy Making": "정책 결정",
        "Policy Implementation": "정책 집행",
        "Policy Evaluation": "정책 평가",
        "Welfare Policy": "복지 정책",
        "Economic Policy": "경제 정책",
        "Foreign Policy": "외교 정책",
        "Defense Policy": "국방 정책",
        "Environmental Policy": "환경 정책",
        "Coalition Government": "연립 정부",
        "Minority Government": "소수 정부",
        "Parliamentary System": "의원내각제",
        "Presidential System": "대통령제",
        "Semi-presidential System": "이원집정부제",
        "Devolution": "권한 이양",
        "Decentralization": "분권화",
        "Local Government": "지방 정부",
        "Constitutional Court": "헌법 재판소",
        "Judicial Review": "사법 심사",
        "Civil Liberties": "시민 자유",
        "Human Rights": "인권",
        "Minority Rights": "소수자 권리",
        "Gender Politics": "젠더 정치",
        "Identity Politics": "정체성 정치",
        "Multiculturalism": "다문화주의",
        "Secularism": "세속주의",
        "Theocracy": "신정주의",
        "Oligarchy": "과두제",
        "Plutocracy": "금권정치",
        "Technocracy": "기술관료제",
        "Meritocracy": "능력주의",
        "Corruption": "부패",
        "Accountability": "책임성",
        "Transparency": "투명성",
        "Good Governance": "좋은 거버넌스",
        "Democratic Backsliding": "민주주의 후퇴",
        "Hybrid Regime": "혼합 체제",
        "Competitive Authoritarianism": "경쟁적 권위주의",
        "Revolution": "혁명",
        "Coup d'état": "쿠데타",
        "Political Violence": "정치적 폭력",
        "Radicalization": "급진화",
        "Democratic Consolidation": "민주주의 공고화",
        "Electoral Integrity": "선거 무결성",
        "Deliberative Democracy": "숙의 민주주의",
    },

    # ─────────────────────────────────────────
    # 예체능 (Arts & Sports)
    # ─────────────────────────────────────────

    "Fine Arts": {
        "Composition": "구도",
        "Perspective": "원근법",
        "Chiaroscuro": "명암법",
        "Hue": "색조",
        "Saturation": "채도",
        "Value": "명도",
        "Texture": "질감",
        "Medium": "매체",
        "Canvas": "캔버스",
        "Pigment": "안료",
        "Impressionism": "인상주의",
        "Expressionism": "표현주의",
        "Abstract": "추상",
        "Figurative": "구상",
        "Portrait": "초상화",
        "Landscape": "풍경화",
        "Still Life": "정물화",
        "Sculpture": "조각",
        "Installation": "설치미술",
        "Critique": "비평",
        "Contour Line": "윤곽선",
        "Cross-hatching": "교차 해칭",
        "Shading": "명암 표현",
        "Foreshortening": "단축법",
        "Negative Space": "부정 공간",
        "Positive Space": "긍정 공간",
        "Color Wheel": "색상환",
        "Complementary Colors": "보색",
        "Analogous Colors": "유사색",
        "Warm Colors": "난색",
        "Cool Colors": "한색",
        "Monochromatic": "단색조",
        "Tint": "색조(흰색 혼합)",
        "Shade": "음영(검정 혼합)",
        "Tone": "중간 색조",
        "Fresco": "프레스코화",
        "Tempera": "템페라",
        "Watercolor": "수채화",
        "Oil Painting": "유화",
        "Acrylic": "아크릴화",
        "Printmaking": "판화",
        "Lithography": "석판화",
        "Etching": "에칭",
        "Screen Printing": "실크스크린",
        "Collage": "콜라주",
        "Mixed Media": "혼합 재료",
        "Photography": "사진",
        "Video Art": "비디오 아트",
        "Performance Art": "퍼포먼스 아트",
        "Conceptual Art": "개념 미술",
        "Street Art": "스트리트 아트",
        "Graffiti": "그래피티",
        "Pop Art": "팝 아트",
        "Surrealism": "초현실주의",
        "Dadaism": "다다이즘",
        "Cubism": "입체주의",
        "Fauvism": "야수파",
        "Baroque": "바로크",
        "Renaissance": "르네상스",
        "Romanticism": "낭만주의",
        "Realism": "사실주의",
        "Minimalism": "미니멀리즘",
        "Abstract Expressionism": "추상 표현주의",
        "Postmodernism": "포스트모더니즘",
        "Contemporary Art": "현대 미술",
        "Curation": "큐레이션",
        "Gallery": "갤러리",
        "Exhibition": "전시",
        "Artist Statement": "작가 노트",
        "Portfolio": "포트폴리오",
        "Patronage": "후원",
        "Auction": "경매",
        "Provenance": "작품 출처",
        "Forgery": "위작",
        "Conservation": "보존",
        "Restoration": "복원",
        "Art History": "미술사",
        "Iconography": "도상학",
        "Iconology": "도상해석학",
        "Formalism": "형식주의",
        "Aesthetics": "미학",
        "Sublime": "숭고미",
        "Beauty": "아름다움",
        "Grotesque": "그로테스크",
        "Semiotics": "기호학",
        "Deconstruction": "해체",
        "Gaze": "응시",
        "Representation": "재현",
        "Identity": "정체성",
        "Body Art": "신체 예술",
        "Land Art": "대지 예술",
        "Site-specific Art": "장소 특정 미술",
        "Relational Aesthetics": "관계 미학",
        "New Media Art": "뉴미디어 아트",
        "Digital Art": "디지털 아트",
        "Generative Art": "생성 예술",
        "Interactive Art": "인터랙티브 아트",
        "Outsider Art": "아웃사이더 아트",
        "Folk Art": "민속 예술",
        "Public Art": "공공 미술",
    },

    "Graphic Design": {
        "Typography": "타이포그래피",
        "Layout": "레이아웃",
        "Grid": "그리드",
        "Hierarchy": "위계",
        "Contrast": "대비",
        "Alignment": "정렬",
        "White Space": "여백",
        "Color Theory": "색채 이론",
        "Brand Identity": "브랜드 아이덴티티",
        "Logo": "로고",
        "Icon": "아이콘",
        "Vector": "벡터",
        "Raster": "래스터",
        "Resolution": "해상도",
        "CMYK": "CMYK(인쇄 색상 모드)",
        "RGB": "RGB(화면 색상 모드)",
        "Mockup": "목업",
        "Prototype": "프로토타입",
        "User Interface": "사용자 인터페이스",
        "User Experience": "사용자 경험",
        "Typeface": "서체",
        "Font": "폰트",
        "Serif": "세리프",
        "Sans-serif": "산세리프",
        "Kerning": "자간 조정",
        "Leading": "행간",
        "Tracking": "자폭",
        "Baseline": "기준선",
        "Cap Height": "대문자 높이",
        "X-height": "소문자 높이",
        "Ascender": "어센더",
        "Descender": "디센더",
        "Legibility": "가독성",
        "Readability": "읽기 편안함",
        "Body Text": "본문 텍스트",
        "Display Type": "제목 서체",
        "Drop Cap": "드롭 캡",
        "Color Palette": "색상 팔레트",
        "Hue": "색상",
        "Saturation": "채도",
        "Brightness": "밝기",
        "Opacity": "불투명도",
        "Blending Mode": "혼합 모드",
        "Layer": "레이어",
        "Mask": "마스크",
        "Clipping Path": "클리핑 패스",
        "Stroke": "획",
        "Fill": "채우기",
        "Gradient": "그라데이션",
        "Texture": "질감",
        "Pattern": "패턴",
        "Composition": "구성",
        "Balance": "균형",
        "Proximity": "근접성",
        "Repetition": "반복",
        "Visual Flow": "시각적 흐름",
        "Focal Point": "초점",
        "Negative Space": "여백 공간",
        "Scale": "크기 비율",
        "Proportion": "비례",
        "Symmetry": "대칭",
        "Asymmetry": "비대칭",
        "Visual Weight": "시각적 무게감",
        "Infographic": "인포그래픽",
        "Data Visualization": "데이터 시각화",
        "Illustration": "일러스트레이션",
        "Photography Direction": "사진 연출",
        "Art Direction": "아트 디렉션",
        "Creative Brief": "크리에이티브 브리프",
        "Mood Board": "무드보드",
        "Style Guide": "스타일 가이드",
        "Brand Book": "브랜드 북",
        "Print Design": "인쇄 디자인",
        "Editorial Design": "에디토리얼 디자인",
        "Packaging Design": "패키지 디자인",
        "Signage": "사이니지",
        "Environmental Graphic Design": "환경 그래픽 디자인",
        "Motion Graphics": "모션 그래픽",
        "Animation": "애니메이션",
        "Storyboard": "스토리보드",
        "3D Typography": "3D 타이포그래피",
        "Responsive Design": "반응형 디자인",
        "Wireframe": "와이어프레임",
        "Design System": "디자인 시스템",
        "Accessibility": "접근성",
        "Contrast Ratio": "명도 대비율",
        "Color Blindness": "색각 이상",
        "Inclusive Design": "포용적 디자인",
        "Print Resolution": "인쇄 해상도",
        "DPI": "DPI(인치당 픽셀 수)",
        "PPI": "PPI(인치당 픽셀)",
        "Bleed": "재단 여분",
        "Trim": "재단선",
        "Margin": "여백",
        "Column": "단",
        "Gutter": "단 간격",
        "Baseline Grid": "기준선 격자",
        "Golden Ratio": "황금 비율",
        "Visual Identity": "시각적 정체성",
        "Iconography": "아이코노그래피",
    },

    "Industrial Design": {
        "Ergonomics": "인체공학",
        "Form": "형태",
        "Function": "기능",
        "Prototype": "프로토타입",
        "Material": "소재",
        "Manufacturing Process": "제조 공정",
        "Sustainability": "지속 가능성",
        "User-centered Design": "사용자 중심 설계",
        "Ideation": "아이디어 발상",
        "Sketch": "스케치",
        "3D Modeling": "3D 모델링",
        "CAD": "컴퓨터 지원 설계",
        "Product Lifecycle": "제품 수명 주기",
        "Aesthetics": "심미성",
        "Usability": "사용성",
        "Tolerance": "공차",
        "Assembly": "조립",
        "Injection Molding": "사출 성형",
        "Rendering": "렌더링",
        "Market Research": "시장 조사",
        "Design Thinking": "디자인 씽킹",
        "Empathize": "공감",
        "Define": "문제 정의",
        "Ideate": "아이디에이션",
        "Test": "검증",
        "Iterate": "반복 개선",
        "Concept Development": "개념 개발",
        "Design Brief": "디자인 브리프",
        "Benchmark": "벤치마크",
        "Competitive Analysis": "경쟁 분석",
        "User Research": "사용자 연구",
        "Persona": "페르소나",
        "Scenario": "시나리오",
        "Use Case": "사용 사례",
        "Storyboard": "스토리보드",
        "Mockup": "목업",
        "Foam Model": "폼 모형",
        "CNC Machining": "CNC 가공",
        "3D Printing": "3D 프린팅",
        "Rapid Prototyping": "신속 시제품 제작",
        "Mold": "금형",
        "Die Casting": "다이 캐스팅",
        "Sheet Metal": "판금",
        "Extrusion": "압출",
        "Blow Molding": "블로우 성형",
        "Thermoforming": "열성형",
        "Finishing": "표면 처리",
        "Anodizing": "양극 산화 처리",
        "Powder Coating": "분체 도장",
        "Plating": "도금",
        "Texture": "표면 질감",
        "Color Development": "색상 개발",
        "CMF Design": "CMF 디자인(색상·소재·표면처리)",
        "Plastic": "플라스틱",
        "Metal": "금속",
        "Wood": "목재",
        "Rubber": "고무",
        "Textile": "섬유",
        "Composite": "복합 소재",
        "Bioplastic": "바이오 플라스틱",
        "Recyclability": "재활용 가능성",
        "Upcycling": "업사이클링",
        "Cradle-to-Cradle": "요람에서 요람으로",
        "Life Cycle Assessment": "생애 주기 평가",
        "Carbon Footprint": "탄소 발자국",
        "Anthropometry": "인체 측정학",
        "Biomechanics": "생체역학",
        "Cognitive Ergonomics": "인지 인체공학",
        "Affordance": "어포던스",
        "Feedback": "피드백",
        "Signifier": "신호 요소",
        "Mental Model": "멘탈 모델",
        "Design Language": "디자인 언어",
        "Form Factor": "폼 팩터",
        "Line": "선",
        "Plane": "면",
        "Volume": "볼륨",
        "Proportion": "비례",
        "Symmetry": "대칭",
        "Tension": "긴장감",
        "Flow": "흐름",
        "Wayfinding": "길 안내 시스템",
        "Universal Design": "유니버설 디자인",
        "Inclusive Design": "포용적 디자인",
        "Design Patent": "디자인 특허",
        "Intellectual Property": "지식 재산",
        "Design Award": "디자인 상",
        "Design Management": "디자인 경영",
        "Design Strategy": "디자인 전략",
        "Brand Experience": "브랜드 경험",
        "Service Design": "서비스 디자인",
        "System Design": "시스템 디자인",
        "Interaction Design": "인터랙션 디자인",
        "Interface Design": "인터페이스 디자인",
        "Wearable Technology": "웨어러블 기술",
        "Internet of Things": "사물 인터넷",
        "Smart Product": "스마트 제품",
        "Circular Economy": "순환 경제",
        "Material Library": "소재 라이브러리",
        "Human Factors": "인간 공학 요소",
    },

    "Music Composition": {
        "Harmony": "화성",
        "Melody": "선율",
        "Rhythm": "리듬",
        "Tempo": "빠르기",
        "Dynamics": "강약",
        "Timbre": "음색",
        "Counterpoint": "대위법",
        "Chord": "화음",
        "Scale": "음계",
        "Key Signature": "조표",
        "Time Signature": "박자표",
        "Modulation": "전조",
        "Cadence": "종지",
        "Motif": "동기",
        "Theme": "주제",
        "Variation": "변주",
        "Orchestration": "관현악법",
        "Notation": "악보 표기",
        "Polyphony": "다성음악",
        "Homophony": "단성 화성 음악",
        "Monophony": "단성음악",
        "Atonality": "무조성",
        "Serialism": "음렬주의",
        "Tonality": "조성",
        "Tonic": "으뜸음",
        "Dominant": "딸림음",
        "Subdominant": "버금딸림음",
        "Leading Tone": "이끔음",
        "Triad": "3화음",
        "Seventh Chord": "7화음",
        "Ninth Chord": "9화음",
        "Suspension": "서스펜션",
        "Resolution": "해결",
        "Voice Leading": "성부 진행",
        "Parallel Motion": "병행 진행",
        "Contrary Motion": "반진행",
        "Oblique Motion": "사행 진행",
        "Dissonance": "불협화음",
        "Consonance": "협화음",
        "Passing Tone": "경과음",
        "Neighbor Tone": "인접음",
        "Appoggiatura": "전타음",
        "Pedal Tone": "페달 톤",
        "Ostinato": "오스티나토",
        "Sequence": "시퀀스",
        "Imitation": "모방",
        "Canon": "카논",
        "Fugue": "푸가",
        "Sonata Form": "소나타 형식",
        "Rondo Form": "론도 형식",
        "Binary Form": "2부 형식",
        "Ternary Form": "3부 형식",
        "Theme and Variations": "주제와 변주",
        "Exposition": "제시부",
        "Development": "발전부",
        "Recapitulation": "재현부",
        "Coda": "코다",
        "Introduction": "서주",
        "Bridge": "교량 악절",
        "Phrase": "악구",
        "Period": "악절",
        "Antecedent": "전악절",
        "Consequent": "후악절",
        "Half Cadence": "반종지",
        "Perfect Authentic Cadence": "완전 정격 종지",
        "Deceptive Cadence": "허위 종지",
        "Plagal Cadence": "변격 종지",
        "Dynamics Marking": "강약 기호",
        "Piano": "여리게(p)",
        "Forte": "세게(f)",
        "Crescendo": "점점 세게",
        "Decrescendo": "점점 여리게",
        "Staccato": "스타카토",
        "Legato": "레가토",
        "Articulation": "아티큘레이션",
        "Vibrato": "비브라토",
        "Tremolo": "트레몰로",
        "Glissando": "글리산도",
        "Trill": "트릴",
        "Fermata": "페르마타",
        "Ritardando": "점점 느리게",
        "Accelerando": "점점 빠르게",
        "Rubato": "루바토",
        "Program Music": "표제 음악",
        "Absolute Music": "절대 음악",
        "Leitmotif": "라이트모티프",
        "Electronic Music": "전자 음악",
        "Sampling": "샘플링",
        "DAW": "디지털 오디오 워크스테이션",
        "MIDI": "MIDI(악기 디지털 인터페이스)",
        "Mixing": "믹싱",
        "Mastering": "마스터링",
        "Arrangement": "편곡",
        "Score": "총보",
        "Part": "파트보",
        "Transposition": "조 바꿈",
        "Enharmonic": "이명동음",
        "Microtone": "미분음",
        "Polyrhythm": "폴리리듬",
        "Syncopation": "당김음",
    },

    "Physical Education": {
        "Cardiovascular Endurance": "심폐 지구력",
        "Muscular Strength": "근력",
        "Flexibility": "유연성",
        "Agility": "민첩성",
        "Coordination": "협응력",
        "Training": "훈련",
        "Aerobic": "유산소",
        "Anaerobic": "무산소",
        "Metabolism": "대사",
        "Nutrition": "영양",
        "Injury Prevention": "부상 예방",
        "Biomechanics": "생체역학",
        "Motor Learning": "운동 학습",
        "Periodization": "기간화 훈련",
        "Recovery": "회복",
        "Sports Psychology": "스포츠 심리학",
        "Team Dynamics": "팀 역학",
        "Tactics": "전술",
        "Fair Play": "페어플레이",
        "Performance Analysis": "퍼포먼스 분석",
        "Warm-up": "준비 운동",
        "Cool-down": "정리 운동",
        "Stretching": "스트레칭",
        "Static Stretching": "정적 스트레칭",
        "Dynamic Stretching": "동적 스트레칭",
        "Resistance Training": "저항 훈련",
        "Plyometrics": "플라이오메트릭스",
        "HIIT": "고강도 인터벌 훈련",
        "Circuit Training": "서킷 트레이닝",
        "Interval Training": "인터벌 트레이닝",
        "Progressive Overload": "점진적 과부하",
        "Specificity": "특이성",
        "Reversibility": "가역성",
        "Overtraining": "과훈련",
        "Detraining": "탈훈련",
        "Tapering": "테이퍼링",
        "Macrocycle": "대주기",
        "Mesocycle": "중주기",
        "Microcycle": "소주기",
        "Muscle Hypertrophy": "근육 비대",
        "Muscle Atrophy": "근육 위축",
        "Fast-twitch Fiber": "속근 섬유",
        "Slow-twitch Fiber": "지근 섬유",
        "VO2 Max": "최대 산소 섭취량",
        "Lactate Threshold": "젖산 역치",
        "Heart Rate": "심박수",
        "Maximum Heart Rate": "최대 심박수",
        "Resting Heart Rate": "안정 심박수",
        "RPE Scale": "운동 자각도",
        "Body Composition": "신체 구성",
        "BMI": "체질량 지수",
        "Body Fat Percentage": "체지방률",
        "Lean Body Mass": "제지방 체중",
        "Caloric Expenditure": "칼로리 소모",
        "Energy System": "에너지 시스템",
        "ATP-PC System": "ATP-PC 시스템",
        "Glycolytic System": "해당 시스템",
        "Oxidative System": "산화 시스템",
        "DOMS": "지연성 근육통",
        "Inflammation": "염증",
        "RICE Method": "RICE 처치법",
        "Sports Medicine": "스포츠 의학",
        "Physical Therapy": "물리 치료",
        "Kinesiology": "운동학",
        "Motor Development": "운동 발달",
        "Fundamental Movement Skills": "기초 운동 기술",
        "Balance": "균형",
        "Power": "파워",
        "Speed": "속도",
        "Reaction Time": "반응 시간",
        "Endurance": "지구력",
        "Stamina": "체력",
        "Physical Fitness": "체력",
        "Health-related Fitness": "건강 관련 체력",
        "Skill-related Fitness": "기술 관련 체력",
        "Motivation": "동기",
        "Goal Setting": "목표 설정",
        "Visualization": "심상 훈련",
        "Concentration": "집중력",
        "Anxiety Management": "불안 관리",
        "Cohesion": "응집력",
        "Leadership": "리더십",
        "Sportsmanship": "스포츠맨십",
        "Officiating": "심판",
        "Doping": "도핑",
        "Anti-doping": "반도핑",
        "Adaptive Sports": "장애인 스포츠",
        "Paralympic": "패럴림픽",
        "Inclusion": "통합",
        "Physical Activity": "신체 활동",
        "Sedentary Behavior": "좌식 행동",
        "Health Promotion": "건강 증진",
        "Physical Literacy": "신체적 소양",
        "Exercise Physiology": "운동 생리학",
        "Strength and Conditioning": "근력 및 컨디셔닝",
        "Functional Movement": "기능적 움직임",
        "Proprioception": "고유 수용성 감각",
        "Hydrotherapy": "수치료",
        "Cross-training": "복합 훈련",
        "Sport Nutrition": "스포츠 영양학",
    },

    "Film & Digital Media": {
        "Cinematography": "촬영술",
        "Editing": "편집",
        "Narrative": "서사",
        "Screenplay": "시나리오",
        "Direction": "연출",
        "Mise-en-scène": "미장센",
        "Montage": "몽타주",
        "Storyboard": "스토리보드",
        "Post-production": "후반 작업",
        "Visual Effects": "시각 효과",
        "Sound Design": "음향 디자인",
        "Color Grading": "색 보정",
        "Documentary": "다큐멘터리",
        "Genre": "장르",
        "Auteur": "작가주의",
        "Distribution": "배급",
        "Streaming": "스트리밍",
        "Frame Rate": "프레임 속도",
        "Resolution": "해상도",
        "Digital Asset": "디지털 자산",
        "Shot": "쇼트",
        "Scene": "씬",
        "Sequence": "시퀀스",
        "Cut": "컷",
        "Continuity Editing": "연속성 편집",
        "Jump Cut": "점프 컷",
        "Cross-cutting": "교차 편집",
        "Parallel Editing": "병렬 편집",
        "Match Cut": "매치 컷",
        "Smash Cut": "스매시 컷",
        "Fade": "페이드",
        "Dissolve": "디졸브",
        "Wipe": "와이프",
        "Long Shot": "롱 쇼트",
        "Medium Shot": "미디엄 쇼트",
        "Close-up": "클로즈업",
        "Extreme Close-up": "익스트림 클로즈업",
        "Establishing Shot": "설정 쇼트",
        "Point of View Shot": "시점 쇼트",
        "Reaction Shot": "반응 쇼트",
        "Over-the-shoulder Shot": "오버 더 숄더 쇼트",
        "Two Shot": "투 쇼트",
        "Insert Shot": "삽입 쇼트",
        "Camera Movement": "카메라 움직임",
        "Pan": "팬",
        "Tilt": "틸트",
        "Dolly": "달리",
        "Tracking Shot": "트래킹 쇼트",
        "Crane Shot": "크레인 쇼트",
        "Handheld": "핸드헬드",
        "Steadicam": "스테디캠",
        "Drone Shot": "드론 쇼트",
        "Depth of Field": "피사계 심도",
        "Shallow Focus": "얕은 초점",
        "Deep Focus": "깊은 초점",
        "Rack Focus": "초점 이동",
        "Aperture": "조리개",
        "Shutter Speed": "셔터 속도",
        "ISO": "감도",
        "White Balance": "화이트 밸런스",
        "Lighting": "조명",
        "Three-point Lighting": "3점 조명",
        "Key Light": "주조명",
        "Fill Light": "보조 조명",
        "Back Light": "역광 조명",
        "Natural Light": "자연광",
        "High Key": "하이 키",
        "Low Key": "로우 키",
        "Chiaroscuro": "명암 대비",
        "Production Design": "미술 설계",
        "Set Design": "세트 디자인",
        "Props": "소품",
        "Costume Design": "의상 디자인",
        "Makeup": "분장",
        "Casting": "캐스팅",
        "Audition": "오디션",
        "Acting": "연기",
        "Method Acting": "메소드 연기",
        "Voice Acting": "성우 연기",
        "ADR": "후시 녹음",
        "Foley": "폴리(효과음 제작)",
        "Score": "음악 스코어",
        "Soundtrack": "사운드트랙",
        "Diegetic Sound": "다이에제틱 사운드",
        "Non-diegetic Sound": "논다이에제틱 사운드",
        "VFX": "시각 효과",
        "CGI": "컴퓨터 그래픽 이미지",
        "Green Screen": "그린스크린",
        "Motion Capture": "모션 캡처",
        "Pre-production": "사전 제작",
        "Production": "제작",
        "Independent Film": "독립 영화",
        "Blockbuster": "블록버스터",
        "Film Festival": "영화제",
        "Pitch": "피치(기획 발표)",
        "Logline": "로그라인",
        "Climax": "클라이맥스",
        "Character Arc": "캐릭터 아크",
        "Protagonist": "주인공",
        "Antagonist": "악당",
    },

    "Fashion Design": {
        "Silhouette": "실루엣",
        "Draping": "드레이핑",
        "Textile": "직물",
        "Pattern Making": "패턴 제작",
        "Haute Couture": "오트 쿠튀르",
        "Ready-to-Wear": "기성복",
        "Trend": "트렌드",
        "Collection": "컬렉션",
        "Mood Board": "무드보드",
        "Lookbook": "룩북",
        "Sustainability": "지속 가능성",
        "Upcycling": "업사이클링",
        "Brand Identity": "브랜드 아이덴티티",
        "Color Palette": "컬러 팔레트",
        "Fabrication": "소재 구성",
        "Sewing": "봉제",
        "Seam": "솔기",
        "Hem": "단",
        "Runway": "런웨이",
        "Fashion Week": "패션 위크",
        "Sketch": "스케치",
        "Flat Drawing": "플랫 도식화",
        "Technical Drawing": "테크니컬 드로잉",
        "Toile": "토일(가봉용 원단)",
        "Muslin": "머슬린",
        "Fitting": "가봉",
        "Alteration": "수선",
        "Basting": "시침질",
        "Dart": "다트",
        "Pleat": "플리트",
        "Tuck": "턱",
        "Gusset": "거싯",
        "Lining": "안감",
        "Interlining": "심지",
        "Interfacing": "접착 심지",
        "Zipper": "지퍼",
        "Button": "단추",
        "Hook and Eye": "훅과 아이",
        "Snap": "스냅",
        "Elastic": "고무줄",
        "Selvage": "식서",
        "Grain Line": "올 방향",
        "Bias Cut": "바이어스 재단",
        "Weave": "직조",
        "Knit": "니트",
        "Woven": "우븐",
        "Natural Fiber": "천연 섬유",
        "Synthetic Fiber": "합성 섬유",
        "Cotton": "면",
        "Wool": "모",
        "Silk": "실크",
        "Linen": "린넨",
        "Polyester": "폴리에스터",
        "Nylon": "나일론",
        "Leather": "가죽",
        "Denim": "데님",
        "Chiffon": "시폰",
        "Organza": "오간자",
        "Velvet": "벨벳",
        "Satin": "새틴",
        "Tweed": "트위드",
        "Jersey": "저지",
        "Spandex": "스판덱스",
        "Dye": "염색",
        "Print": "프린트",
        "Embroidery": "자수",
        "Appliqué": "아플리케",
        "Beading": "비딩",
        "Pleating": "주름 가공",
        "Smocking": "스모킹",
        "Quilting": "퀼팅",
        "Fashion Forecasting": "패션 예측",
        "WGSN": "WGSN(트렌드 예측 서비스)",
        "Fast Fashion": "패스트 패션",
        "Slow Fashion": "슬로 패션",
        "Capsule Wardrobe": "캡슐 워드로브",
        "Vintage": "빈티지",
        "Resale": "리세일",
        "Circular Fashion": "순환 패션",
        "Fashion Merchandising": "패션 머천다이징",
        "Buying": "바잉",
        "Visual Merchandising": "비주얼 머천다이징",
        "Retail": "소매",
        "Wholesale": "도매",
        "Fashion Photography": "패션 사진",
        "Styling": "스타일링",
        "Accessory": "액세서리",
        "Footwear": "신발",
        "Millinery": "모자 제작",
        "Activewear": "액티브웨어",
        "Lingerie": "란제리",
        "Menswear": "남성복",
        "Womenswear": "여성복",
        "Childrenswear": "아동복",
        "Unisex": "유니섹스",
        "Gender-neutral Fashion": "젠더 뉴트럴 패션",
        "Size Inclusivity": "사이즈 다양성",
        "Fashion Ethics": "패션 윤리",
        "Sustainable Textile": "지속 가능 섬유",
        "Fashion Technology": "패션 테크놀로지",
    },
}
